django-import-export/django-import-export

AUTHORS, import_export/resources.py, tests/core/tests/resources_tests.py
=> Automatically add missing fields to the end of `export_order`.

docs/settings.rst, import_export/admin.py
We found out adding admin log is very slow(about 5 minutes or even more) when one csv file of about 3000 lines with about 20 columns is imported. When sqlite3 backend is in use, the import is extremely slow, it's also slow on MySQL for the log entries contains lots of plain text.
=> Add skip admin log option when importing

.travis.yml, tox.ini
As Django 1.8 is coming and the latest stable version of Python is the version 3.4.3, `tox.ini` and Travis CI should support these versions
PR related to issue #200 .
=> Add Python 3.4 and Django 1.8 to tox and Travis CI

import_export/admin.py
Option available starting on django 1.7. Starting on django 1.8,
"each_context" requires the request as a parameter.
=> update context with admin vars. Fixes #213

AUTHORS, import_export/fields.py, tests/core/tests/resources_tests.py
When you have a readonly field in a ModelResource that gets its data from an annotated value (via `get_queryset` in ModelAdmin), you get AttributeErrors for each row during importing. This should fix that.
=> Fix AttributeErrors when importing readonly fields from annotated values

import_export/fields.py, tests/core/tests/fields_tests.py
This code allows relation following also on save. It's even possible to support m2m relations with customization such as:
```
def init_instance(self, row=None):
obj = self._meta.model()
obj.pk = 1
return obj
```
cc @bmihelac
=> Allow Field.save() relation following

import_export/admin.py, tests/urls.py
Django 1.9 gives lots of deprecation warning in logs.
Source: https://docs.djangoproject.com/en/1.9/internals/deprecation/#deprecation-removed-in-1-10
=> Remove django.conf.urls.patterns as it will be removed in Django 1.10

import_export/fields.py, tests/core/models.py, tests/core/tests/resources_tests.py
some fields need to utilize a dynamic callable for their default
values.  for example a field with a current timestamp, a random
string or maybe a UUID.
the current Field.clean method is caching the first invocation of
the default callable, so later uses of this field only use the cached
value.  this fix removes the caching element, so each time the default
value is needed, the callable is invoked.
=> fix for fields with a dyanmic default callable

.travis.yml, import_export/resources.py, tests/core/tests/resources_tests.py, tox.ini
If a db exception (such as `Key (name, primary_contact)=(squaberblabeergabatersh, Jenny Susans) already exists.` is thrown during Resource.import_data (when we try to save the instance), then attempting to rollback the database may result in
```TransactionManagementError “You can't execute queries until the end of the 'atomic' block” ```, causing import_data to throw an unhelpful transaction exception. With this fix the function will exit cleanly and the db error will be returned in one of the row_results as intended.
No time to add a failing test at the moment, but hopefully this is sufficient information to go on..
=> Let Resource rollback if import throws exception

.isort.cfg
Keep this file in the project's top level directory so that when isort is run on files in this project it will follow the rules set out in the config. Many editors also have a python-isort plugin, so that you can even enable automatic sorting on save in your favourite editor.
I've set the config to use 6 sections:
- future
- stdlib (including non-webby third party apps that you can specify yourself; I've added tablib to this section)
- webby third party apps
- django (django imports are usually extensive enough to warrant giving them their own section rather than mixing them with other third-party apps)
- first party (anything importing from 'import_export')
- local folder (any relative import, ie. starting with a dot)
But this is just how I like to set things out. By all means go ahead …
=> Add .isort.cfg

import_export/resources.py
In case of debugging import errors, not limiting the traceback makes debugging easier. I have the limit disabled when debugging allegro/ralph#2187, and it helps me to locate the code in question.
=> [Proposal] Do not limit traceback depth.

import_export/admin.py
As far as I understand the whole unicode/encoding a file cannot be "in unicode" because it just consists of bytes which carry text information saved through a particular encoding table (i.e. UTF-8, etc.). 
I don't want to nitpick but it took me a while to wrap my head around the whole UnicodeDecodeErrors and implicit conversion that I don't want further misinformation to spread. In case I'm mistaken, please correct me and just close this pull request.
=> Change error message wording on UnicodeDecodeError

import_export/resources.py, requirements/dev.txt, tests/core/tests/resources_tests.py, tests/settings.py
This addresses https://github.com/django-import-export/django-import-export/issues/59.
The problem:
I have created an example repository at https://github.com/sgarcialaguna/import-example which demonstrates the bug. The problem occurs with the latest django-import-export and PostgreSQL 9.5
The repository contains a simple model Widget which has nothing but an auto-increment field:
```python
class Widget(models.Model):
pass
```
Set up the project and the database, then go into the admin interface and import the widgets via the contained widgets.csv (it just creates a widget with the id 1)
Now create a new widget via the admin interface and there's an Integrity Error as Django tries to create a widget with id 1, but 1 is already assigned. 
You can manually repair the situation by running …
=> Reset SQL sequences when new objects are imported

import_export/admin.py
The argument for the error message was "e" not the name of file to be imported.
As a result the message did not show any file name.
=> Error message did not show filename

docs/configuration.rst, import_export/admin.py, import_export/static/import_export/action_formats.js
Hi,
This little javascript hides the formats select and shows it only when the export action is selected. It is quite simple but IMHO a good usability improvement.
Should you like the idea, we also need to modify the documentation to include the collectstatic step in the installation.
=> show formats selector only when export action is selected

AUTHORS, import_export/templates/admin/import_export/change_list_import.html, tests/core/admin.py, tests/core/tests/admin_integration_tests.py
Using ImportMixin does not display the import button for users who do not have explicit add permissions (unlike ImportExportMixin or ExportMixin, which display buttons regardless).
This is because ImportMixin uses the django admin/change_list template, while ImportExportMixin and ExportMixin use django-import-export's change_list template. For consistency I updated so that they all use django-import-export's template.
I added AuthorAdmin to the admin panel using the ImportMixin and added a test to admin_integration_tests (test_import_buttons_visible_without_add_permission). The test checks that a user without add permissions can see the import button. It also verifies that the correct template is loaded.
The first branch results in a failing test; the second branch contains the template …
=> ImportMixin does not display the import button in admin for users w/o add permissions

import_export/resources.py, import_export/templates/admin/import_export/import.html
Using the object representations in line errors hinders comprehensibility a lot because there's `OrderedDict([…])` and lots of `u'…'` obfuscating what really matters. 
These small changes make the error output a bit more pleasing to the end user.
---
On a different note: 
I wonder if it really is such a good idea to include the whole traceback with the errors on each line. As it contains information about the runtime environment and about script paths this 
- might be a security risk
- is more unhelpful than handy because it creates lots of noise compared to the more precise message in the exception itself.
But this is just my opinion and as everyone can just edit the template in their `Resource` this might not be of relevance.
=> Make line errors more readable

import_export/admin.py, tests/core/tests/admin_integration_tests.py
When importing large lists, it would be helpful for admin to quickly see a count of the total number of new objects versus the updated objects that were already in the database.
I added these counts to the success message that occurs after importing in the admin panel.
=> Add total counts to import success msg

AUTHORS, docs/getting_started.rst, import_export/admin.py, import_export/signals.py
I want to do some action after the import process is done.
I can not find the hooks.
So, I added to signal `post_import`, `post_export`.
the hook can be add like this:
from django.dispatch import receiver
from import_export.signals import post_import, post_export
@receiver(post_import, dispatch_uid='balabala...')
def _post_import(model, **kwargs):
pass
@receiver(post_export, dispatch_uid='balabala...')
def _post_export(model, **kwargs):
pass
=> add signal post_import, post_export to fire events

import_export/resources.py, tests/core/tests/resources_tests.py
When importing a new instance that has a field with a default value, the preview diff shows a red deletion for the default value:
Since the instance is new, the diff should instead just highlight the new value, since nothing is being deleted. For rows that don't change the default value, continue to show the value without any highlighting:
=> Hide default value in diff when importing a new instance

import_export/resources.py, tests/core/fixtures/category.yaml, tests/core/tests/resources_tests.py
Diffs are incorrect for objects with `RelatedManager` attributes since the lookup (using `export_field()`) obtains the same values for both `original` and `current`. To fix this, the fields in `original` need to be exported before `import_obj()` is called.
=> Fix diff for objects with RelatedManager attributes

import_export/widgets.py
There are situations where the imported data is not a string, but data that is already cleaned. In such situations we should not try to parse the data.
=> Handle already cleaned objects

import_export/formats/base_formats.py
I was wondering why it takes so long to import 4000 rows long xlsx file with only two columns, made some measurements and it turned out it takes around 150 second only to populate dataset. Found out there's [optimized way for read-only mode](http://openpyxl.readthedocs.io/en/default/optimized.html#read-only-mode) in `openpyxl`.
So here's a little enhancement to make use of it. On my machine it reduced read time to 0.5 seconds for the same file so I thought it might be useful to others.
Unit test for it is already there, let me know if you want some performance reports or something (tbh I'm not sure how to "officially" prove performance boost 😶 ).
=> Use optimized xlsx reader

import_export/resources.py, tests/core/tests/resources_tests.py
=> Add diff class to generate diff HTML (and fix build)

import_export/fields.py, import_export/widgets.py, tests/core/tests/widgets_tests.py
_I accidentally force-pushed/deleted the original pull request branch and as I don't have the means to reopen [the previous pull request](https://github.com/django-import-export/django-import-export/pull/420) I'm opening a new one. Please excuse this._
This pull request adds a `get_queryset()` method to `ForeignKeyWidget` and makes `fields.Field` pass row data on to the widgets so that the queryset can be narrowed down in case `ForeignKeyWidget.field` is not unique on its own.
The `obj` is exposed to `widget.export()` as a kwarg as well.
This pull request is related to the following issues: #375 #188 #378 
All tests pass on current master branch.
=> Fix #375: add row to widget.clean(), obj to widget.render()

README.rst
The links to read the docs are currently pointing to the latest version, currently 98 commits ahead of the latest release. Some hooks have been added (e.g. `before_import_row` on the `Resource`) and are therefore documented but not present in the latest version installable with `pip`.
Suggest to update the links in README to the stable one. Also to be updated in the repository description.
I also updated the URLs according to their [blog post from the 27th April](https://blog.readthedocs.com/securing-subdomains/):
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
=> Update doc links to the stable version, update rtfd to .io

.travis.yml, import_export/admin.py, import_export/resources.py, import_export/results.py, tests/core/tests/resources_tests.py
With transactionality restored, add a flag to tell `process_import()` to collect rows that fail to import in a `Dataset`. We use this to save the failed rows to a file, and then allow the user to download the file to see what rows failed, and with what error message.
=> Collect failed rows

import_export/results.py
Unless I'm misunderstanding something, the `Exception` class' `message` attribute has been removed in python 2.7/3.0 (at least according to https://www.python.org/dev/peps/pep-0352/#retracted-ideas).
Exceptions should now be converted to strings using `str()`.
This caused an error for me when when a `ValueError` was caught during a dry run with `collect_failed_rows=True`. I'm running Python 3.4.3.
=> Error in converting exceptions to strings

import_export/admin.py
This refactoring allows imports to be done asynchronously (in our case, using celery). We've been using this for months now, and I thought it was finally time to push the changes back upstream.
=> Process import dataset and result in separate methods

.gitignore, AUTHORS, docs/api_widgets.rst, import_export/resources.py, import_export/widgets.py, tests/core/tests/widgets_tests.py
Django 1.8 added the [DurationField](https://docs.djangoproject.com/en/1.10/ref/models/fields/#durationfield) which allows storing of a time duration (a Python [timedelta](https://docs.python.org/2/library/datetime.html#datetime.timedelta)).
Since there's no standard built-in parsing of `timedelta`, I'm tying this to Django's `DurationField` and using the [parse_duration](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.dateparse.parse_duration) helper.  This means it won't be supported on Django < 1.8, but this change handles that by ignoring them.
_Also adding `/django-import-export/` to gitignore because the tests create files there._
=> Add support for the Django DurationField with DurationWidget.

.gitignore, import_export/resources.py
`Resource.import_row` defines using_transaction, dry_run as keyword arguments. But when calling it they are send as positional arguments.
So if We don't need any of those keyword arguments We shouldn't have to define them in my overriden import_row function.
The below usage is not possible with the current implementation.
```python
class MyResourse(ModelResource):
def import_row(self, row, instance_loader, dry_run=False, **kwargs):
...
```
We have to write
```python
def import_row(self, row, instance_loader, using_transactions=False, dry_run=False, **kwargs):
```
or
```python
def import_row(self, row, instance_loader, using_transactions, dry_run, **kwargs):
```
=> Refactor import_row call by using keyword arguments.

AUTHORS, import_export/admin.py
Allows overriding `get_import_form()` to change the form used.
=> Make import form type easier to override

docs/getting_started.rst
Single colon instead of double to introduce code section
=> Make Signals code example format correctly

setup.py
As django is imported by the library and is a hard runtime requirement, it should be listed as a requirement in setup.py for completeness.
=> Add Django as requirement to setup.py

import_export/admin.py
According to https://docs.djangoproject.com/en/1.11/ref/urlresolvers/:
> In older versions, these functions are located in django.core.urlresolvers. Importing from the old location will continue to work until Django 2.0.
=> Update import of reverse for django 2.x

.travis.yml, import_export/admin.py, import_export/resources.py, tests/core/models.py, tests/urls.py
Fix for #664. Doesn't contain all of the fixes needed for Django 2.0. Any contribution welcome.
=> (unfinished) fixes for Django 2.0

AUTHORS, import_export/widgets.py, tests/core/tests/widgets_tests.py
This makes imports more robust when users enter whitespaces after
commas.
=> Strip whitespace when looking up ManyToMany fields

tests/core/tests/base_formats_tests.py
When running tests with warnings enabled, `-Wall`, `ResourceWarning` will no longer appear. Fixes warnings of the form:
`ResourceWarning: unclosed file <_io.BufferedReader name='...'>`
=> Fix all ResourceWarnings during tests

import_export/instance_loaders.py
Dictionary comprehension has been available since Python 2.7. As django-import-export only supports Python 2.7+ or Python 3.3+, can take advantage of newer, rich Python features.
See Python PEP-0274 for additional details:
https://www.python.org/dev/peps/pep-0274/
=> Replace dict(<list_comprehension>) pattern with dict comprehension

.travis.yml
Helps reduces requests to PyPI.
See TravisCI docs for details on cache:
https://docs.travis-ci.com/user/caching/#pip-cache
=> Add pip caching support to Travis CI configuration

import_export/resources.py, import_export/results.py
`collections.OrderedDict` was added to Python starting with 2.7. As django-import-export only supports Python 2.7+ or Python 3.3+, can safely rely on the stdlib version of `OrderedDict`.
=> Remove workaround for Python 2.6 wrt OrderedDict

import_export/fields.py, import_export/resources.py, tests/core/tests/instance_loaders_tests.py
`iter(dict)` is identical to `iter(dict.keys())`. The call to `.keys()` is unnecessary and only adds noise. Remove these unnecessary calls.
Inspired by Lennart Regebro's presentation "Prehistoric Patterns' at PyCon 2017. Available at:
https://www.youtube.com/watch?v=V5-JH23Vk0I
=> Remove unnecessary calls to dict.keys()

.travis.yml
Django 1.11 and newer support Python 3.6.
=> Travis tests for Python 3.6 on Django >= 11

AUTHORS, docs/changelog.rst, tests/settings.py
=> MIDDLEWARE_CLASSES django setting removed in 2.x

tox.ini
Add supported Django versions
Add supported python versions
Use openpyxl==2.4.11 as 2.5.x drops support for python 3.3
=> Upgrade tox configuration

import_export/static/import_export/action_formats.js
`ExportActionModelAdmin` works fine with Django-Grappelli except for one little detail: on valila admin, there is a little jQuery snippet that toggles visibility of the added `file_format` field. Because Grappelli uses different CSS classes and IDs, this toggling does not occur.
This in vanila admin:
... looks like this in grapppelli:
... but in the default state looks like this:
Changes in this PR enable grappelli to benefit from the existing feature in the same way that vanila django-admin does, by hiding the second dropdown in grappelli until the "export" action is selected. Original functionality in vanila admin is not affected.
----
Contributing guidelines... yes I have read them. Cannot comply to most of the requirements there because they assume changes to Python code. Please let …
=> custom js for action form also handles grappelli

import_export/resources.py
I added resource widgets map and default field to make it easy override widgets and default field.
Let me know if its useful or required some extra work.
=> Resource widgets map and resource default field

import_export/formats/base_formats.py
Kept backwards compatibility for python 2.7
=> fixed warning U mode is deprecated in python 3

import_export/resources.py, tests/core/tests/resources_tests.py
The fields resource class attribute is the *class-wide* definition of
fields. Because a particular *instance* of the class might want to
alter self.fields, we create self.fields here by copying cls.fields.
Instances should always modify self.fields; they should not modify
cls.fields.
=> Make deep copy of fileds from class attr to instance attr

.gitignore, AUTHORS, import_export/admin.py, import_export/formats/base_formats.py, import_export/mixins.py, import_export/views.py, tests/core/templates/core/category_list.html, tests/core/tests/mixins.py, tests/core/tests/test.py, tests/core/views.py, tests/urls.py
Created a mixin view to export without admin interface.
I think it would be a really great thing if we have a generic class based views for this application.
I tested this patch with a `ListView` & `django_filters.views.FilterView`.
The 2nd is really useful to replace the `AdminFilters`
=> Added ExportViewMixin

AUTHORS, docs/installation.rst, import_export/admin.py, import_export/templates/admin/import_export/change_list_export_item.html, import_export/templates/admin/import_export/change_list_import_item.html, tests/core/tests/test_permissions.py
Since everybody with `is_staff=True` can execute import and export actions, in this PR i proposed to add these settings:
```
IMPORT_EXPORT_IMPORT_PERMISSION_CODE='add'
IMPORT_EXPORT_EXPORT_PERMISSION_CODE='add'
```
Now, only user with that authorized with specified permission code in settings can import/export.
To disable this, just set both settings into None.
reference #608
=> Add Import Export Permissioning #608

import_export/admin.py
I already have a class inheriting from `ModelAdmin` but I want to use the `ExportActionModelAdmin` logic. So I think it would be better to transform it into a Mixin and still provide the `ExportActionModelAdmin` for more flexibility.
=> Add ExportActionMixin

docs/api_widgets.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
JSONWidget can be used for importing jsonb objects in the PostgreSQL DB.
=> JSONWidget for jsonb fields

import_export/instance_loaders.py
When `import_id_fields` is empty, `get_instance()` should return None. Previously it would return an object if queryset contained a single object -- qs.get() with no args returns an obj for queryset of length=1.
=> Changed `get_instance()` return val

import_export/resources.py
As discussed in #527 (a long time ago) I have modified the logging level from exception to debug.
What is currently happening when using django-import-export on production is that we want to show import errors to the user and we do that in django admin, but besides from these we get loads and loads of errors being reported to Sentry, which we can't really change the configuration for without extending Resource on our end and overriding how `import_data` works inside. Which as a result might disable the possibility to upgrade the library.
I am proposing changing all `logger.exceptions` to `logger.debug` as basically we only need these logging details when testing our code using django-import-export and in all other cases the consuming code should be able to handle the raised exceptions in …
=> Change logging level

setup.py
As recommended by Python docs, use setuptools not distutils. See:
https://docs.python.org/3/library/distutils.html
> Most Python users will not want to use this module directly, but
> instead use the cross-version tools maintained by the Python Packaging
> Authority. In particular, setuptools is an enhanced alternative to
> distutils ...
setuptools is necessary for features like python_requires.
=> Use modern setuptools in setup.py

tests/core/tests/test_resources.py
collections.OrderedDict is available on all supported Pythons
=> Remove outdated workaround for OrderedDict

import_export/formats/base_formats.py
importlib.import_module is available since Python 2.7.
=> Remove workaround for older Pythons

import_export/formats/base_formats.py, requirements/base.txt, tests/core/tests/test_admin_integration.py
As mentioned [here](https://github.com/kennethreitz/tablib/issues/324) and [here](https://github.com/django-import-export/django-import-export/issues/762), openpyxl has changed there api for xlsx.  Currently when exporting to xlsx we receive a 500 error. 
Addresses #762
=> Peg openpyxl dependency to 2.4.9 to avoid non-backwards compatible api change

import_export/admin.py
This unused import was missed in the previous fix.
=> Remove additional unused import

.travis.yml, tests/core/models.py
**Problem**
The `python_2_unicode_compatible` decorator has been removed from the master for a [Django 3.0 release](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis).
And as a result it keeps breaking my other pipelines 😞  
**Solution**
Removed the usage
**Screenshots**
If applicable, add screenshots to help explain your solution.
Please make sure you meet the following.
=> Remove python2 compatibility decorator

.github/.stale.yml
**Problem**
The number of inactive issues and PR are far too many to manage at the moment.  
**Solution**
From the [probot site](https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea):
> In an ideal world with infinite resources, there would be no need for this app.
> 
> But in any successful software project, there's always more work to do than people to do it. As more and more work piles up, it becomes paralyzing. Just making decisions about what work should and shouldn't get done can exhaust all available resources. In the experience of the maintainers of this app—and the hundreds of other projects and organizations that use it—focusing on issues that are actively affecting humans is an effective method …
=> Stale bot config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/stale.yml
**Problem**
Stale bot is pretty aggressive. And the PR/issue templates were a bit confusing.
**Solution**
- scale back stale bot to >90 days.
- simplify the templates
N/A as it is a chore.
=> Scale back stale bots time to stale

tests/core/tests/test_resources.py
Avoid unnecessary string formatting, just call the text function instead.
=> Simplify coerce to text type

import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
JSONWidget gives error when there are null values due to ast.literal_eval which fails to evaluate null as values.
**Solution**
By default, now it will use json to loads and dumps. However if the json string has single quotes instead of double, it will first replace the single quotes to double quotes and then loads.
Tests have included for such cases.
=> JSONWidget updated with null value fix

import_export/static/import_export/import.css
**Problem**
What problem have you solved? Showing error message properly when admin language is rtl.
**Solution**
How did you solve the problem? Removing unnecessary style
I checked it with lrt and rtl mode and both of them now show the error correctly
RTL Before:
RTL After:
LTR After:
=> show error properly in rtl mode

.github/stale.yml
**Problem**
Allow issues to be open longer
**Solution**
Bump the time to 180 days
=> Bump stale bot time to half a year

import_export/admin.py, import_export/mixins.py, tests/core/tests/test_admin_integration.py
**Problem**
There was a bug when export filename contained a space, it was truncated. For example:
`foo bar.csv` resulted just in `foo` filename being served as file.
Also I've found a lack of request instance and queryset while preparing filename. It may also be needed by somebody else, so I've added it.
=> Fix bug with spaces in export filename, pass request and queryset

import_export/resources.py, tests/core/tests/test_resources.py
Fixes #570 and #991. 
Currently, when importing data, errors are raised if any of the fields used to identify existing objects (specified in `Resource.Meta.import_id_fields`) are not present in the uploaded dataset. Because of this, even if uploading an entirely new dataset, users must always remember to include blank columns for each of the id fields.
If the fields specified by `import_id_fields` are not included in the uploaded data, I believe it is safe to assume that all data is new, and attempts to match rows to existing objects should be avoided all together.
Have you written tests? Yes
Have you included screenshots of your changes if applicable? N/A
Did you document your changes? Please advise if updating the docstring is sufficient
=> Assume user is importing new data if id fields not included

import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
Imports fail for the current master because the exception `FieldDoesNotExist` has been moved.
**Solution**
Made import conditional on the Django version.
CI tests should stop failing for the Django master
=> Fix exception import for Django 3

import_export/admin.py
New way of handling admin actions
**Problem**
From Django 2.2 admin actions are no longer collected from base ModelAdmin classes
https://docs.djangoproject.com/en/2.2/releases/2.2/#admin-actions-are-no-longer-collected-from-base-modeladmin-classes
**Solution**
Use new suggested way of adding admin actions
=> Move actions definition to ExportActionMixin

setup.py
**Problem**
The package description is missing a white space. The description is currently showing as `Django application and library for importing and exportingdata with included admin integration.`
**Solution**
Added white space
The description is showing correctly as `Django application and library for importing and exporting data with included admin integration.`
=> Add missing space to description

.travis.yml
=> [py38] Python 3.8 is no longer dev

.travis.yml
**Problem**
Travis started showing errors `ImportError: No module named 'settings'`
**Solution**
Use same export as when running tests script
All good after applying this
=> Travis import error: no module named settings

requirements/base.txt
**Problem**
When running the command  `django-admin migrate` that was ocurring that following error:
```python
Traceback (most recent call last):
File "/app/.heroku/python/bin/django-admin", line 11, in <module>
load_entry_point('Django==2.2.4', 'console_scripts', 'django-admin')()
File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
django.setup()
File "/app/.heroku/python/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate …
```
=> Pin tablib version to not use new major version

docs/api_admin.rst, docs/getting_started.rst, docs/import_workflow.rst, docs/index.rst, docs/installation.rst
Reflow the documentation to an 80 character line limit.
Add a few notes on how `dehydrate_<fieldname>()` works.
=> [Docs] Formatting and example improvements

docs/changelog.rst, docs/installation.rst, import_export/formats/base_formats.py, requirements/base.txt, setup.py, tests/core/tests/test_admin_integration.py, tests/core/tests/test_base_formats.py
This allows to install django-import-export with a subset of all tablib
available formats.
=> Allow tablib to provide format availability

AUTHORS, docs/import_workflow.rst, import_export/resources.py
**Problem**
On the ['Import data workflow' section in the docs](https://django-import-export.readthedocs.io/en/latest/import_workflow.html), there are references to `init_instance` that are not clickable.
**Solution**
The PR adds a doc string to `Resource.init_instance` to make the references clickable.
=> Import data workflow docs - improve references to init_instance

docs/import_workflow.rst
There is a small typo in docs/import_workflow.rst.
Closes #1093
=> docs: Fix simple typo, intitalized -> initialized

AUTHORS, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
When importing a large number of rows (using this [patch](https://github.com/django-import-export/django-import-export/issues/939#issuecomment-509435531)), disabling the diff operation results in ~30% improvement in import time.
**Solution**
This PR involves adding a meta attribute to the Resource, which gives the option of disabling diffing operations.  The default value is `False` meaning existing behaviour is unchanged unless the flag is explicitly set to `True`.
There is a new TestCase in `test_resources.py` which uses patches to verify that `diff` and `copy` functions are not called.
The flag is documented in `resources.py`.
=> Adds meta flag 'skip_diff' to enable skipping of diff operations

docs/celery.rst, docs/index.rst
**Problem**
Long running imports time out.
**Solution**
Moved long running imports to celery
=> Add link to django-import-export-celery in docs

docs/installation.rst
Without that underscore, the link is broken, see https://django-import-export.readthedocs.io/en/latest/installation.html
=> Missing underscore in docs link reference

import_export/admin.py
**Problem**
During the preview dry run, the ImportForm is passed into Resource.get_import_data_kwargs.  However, during the actual import phase the ConfirmImportForm is not passed into the same method.  This means there's no way to get values set in the ConfirmImportForm into the Resource's import process.
**Solution**
Passing the confirm form into `get_import_data_kwargs` during the actual import process.
There are no existing tests that cover this, and no appropriate documentation to update.  I don't think a test case for this is warranted but let me know if I'm wrong!
=> Pass form into get_import_data_kwargs

import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
As [per doc](https://docs.python.org/3/library/decimal.html):
```python
>>> Decimal('3.14')
Decimal('3.14')
>>> Decimal(3.14)
Decimal('3.140000000000000124344978758017532527446746826171875')
```
When Decimal field is initialized from import it gets float value. See updated test case for details (it will fail without this fix).
**Solution**
Force Decimal initialization with text value.
Test case updated, no documentation changes required.
=> Initialize Decimal with text value, fix #1035

import_export/admin.py
**Problem**
`get_import_resource_kwargs` should allow an ImportForm (and ConfirmImportForm) to provide customization of a Resource instance.
`get_import_resource_kwargs` is called in two places:
1. when processing the ImportForm
2. when processing the ConfirmImportForm
The first call passes `form=form` keyword argument, but the latter call does not pass `form=confirm_form`.
**Solution**
I simply set the `form` keyword in the second call to `get_import_resource_kwargs`.
This permits usage like this:
```
class BookAdmin(ImportMixin, admin.ModelAdmin):
...
def get_resource_kwargs(self, request, *args, **kwargs):
form = kwargs['form']
rv = {}
if isinstance(form, BookFormMixin):
if form.is_valid():
author = form.cleaned_data['author']
rv.update({'author': author.pk})
return rv
```
**Acceptance …
=> Make confirm_form accessible in get_import_resource_kwargs

import_export/resources.py
**Problem**
The diff view was showing only data columns that were defined by `get_user_visible_fields` but the column headers were not constrained by `get_user_visible_fields`.
**Solution**
Added get_user_visible_headers which uses `get_user_visible_fields`, and changed `get_diff_headers` to use it.
I have not written tests.  Happy to if other maintainers deem necessary!
=> Make import diff view only show headers for user visible fields

README.rst
**Problem**
Project requirements were defined in README.rst.  This is unnecessary because the requirements are enforced in [`setup.py`](https://github.com/django-import-export/django-import-export/blob/master/setup.py#L25).  See https://github.com/django-import-export/django-import-export/pull/1079
**Solution**
Removed this section entirely.
Simple text change so review should be acceptable.
=> Removed 'requirements' section from README.rst

tox.ini
**Problem**
If you run tox locally with `tox -r`, then it will fail with:
```
NameError: name 'data_field' is not defined
```
This is because the test migration [` 0004_bookwithchapters.py`](https://github.com/django-import-export/django-import-export/blob/master/tests/core/migrations/0004_bookwithchapters.py) references `JSONField` and `ArrayField` which is postgres specific fields.  Hence `psycopg2` is a dependency.
Additionally, the `envlist` in tox.ini was too permissive, and meant that Django 3.0 was being tested against python 3.5, which is only supported by Django 2.*.  
**Solution**
- include a reference to `requirements/test.txt` in tox.ini
- Reformat the `envlist` to correctly reference python / django versions
- I have tested this successfully locally.
- …
=> Fix for tox failing when run locally

import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
https://github.com/django-import-export/django-import-export/issues/1112
> When exporting an object with a `DurationField` that has a value equivalent to `timedelta(0)`, the exported value is blank (`""`), because of the implementation of the `DurationWidget`
> 
>    ```python
> def render(self, value, obj=None):
>         if not value:
>             return ""
>         return str(value)
> ``` 
When `value == datetime.timedelta(0)`, `""` is returned.
This causes issues when re-importing exported data (and even prevents it if the `DurationField` in model class is not nullable).
**Solution**
Fixed by checking if `value is None` instead of relying on implicit conversion to boolean.
Added `test_render_zero`, `test_clean_zero` and `test_clean_none` for …
=> Fix DurationWidget handling of zero value

docs/getting_started.rst
before >> `def get_form_kwargs(self, form, *args, **kwargs)`
after >>> `def get_form_kwargs(self, form, *args, **kwargs):`
**Problem**
syntax error
**Solution**
just added ":" at the end if of  `get_form_kwargs()` function
=> The function was missing ":"

tests/urls.py
**Problem**
1. When running the test app, you get a 404 if you browse to http://localhost:8000/ - which is not user friendly.
2.  The URLs used the [`url()`](https://docs.djangoproject.com/en/2.2/ref/urls/#url) function which is likely to be deprecated in a future Django release.
**Solution**
1. I added a [`RedirectView`](https://docs.djangoproject.com/en/3.0/ref/class-based-views/base/#redirectview) to redirect from the root path to 'admin/'
2. Switched to use [`path()`](https://docs.djangoproject.com/en/2.2/ref/urls/#path) syntax
Ran existing test suite and tested manually.
=> Update demo app urls

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
Deals better with NULL/None values, which are now (Django 2.2) permitted in the regular fields.BooleanField (fields.NullBooleanField has been deprecated). Importing a field with TRUE/FALSE/NULL was otherwise failing (via turning all the NULL's into FALSE's).
**Problem**
The Boolean widget (which is used to diff an re-import) wasn't dealing with Null/None/Empty values, and instead casting them as "0" (i.e. `False`)
**Solution**
Explicitly add `""` (an empty string) and `None` as "None values".
*Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?*
No additional tests. No screenshot. I've added it to the Changelog (under v2.0.2).
=> Exapnd valid values for BooleanWidget

Makefile, requirements/deploy.txt, requirements/dev.txt, requirements/docs.txt, requirements/test.txt
**Problem**
Lots of commands, and they are quite difficult to remember.
**Solution**
Makefile
```
$ make help    
build-html-doc            builds the project documentation in HTML format
clean-build               remove build artifacts
clean-pyc                 remove Python file artifacts
clean-tests               remove pytest artifacts
coverage                  generates codecov report
install-base-requirements install package requirements
install-deploy-requirements install requirements for deployment
install-docs-requirements install requirements for docs
install-test-requirements install requirements for testing
lint                      check style with isort
messages                  generate locale file translations
release                   package and upload a release
sdist …
```
=> Add Makefile

tests/settings.py
**Problem**
Django 3.1’s new admin side bar has added a system check warning at the start of the test run:
```
Creating test database for alias 'default'...
System check identified some issues:
WARNINGS:
?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.
System check identified 1 issue (0 silenced).
...
```
**Solution**
This PR fixes it by following the hint.
No system check warning at the start of the test run.
=> Fix system check warning in tests

tox.ini
**Problem**
Users seeing warnings.
**Solution**
This is a technique I've rolled out against my own open source projects and [Django REST Framework](https://github.com/encode/django-rest-framework/pull/7586).
By failing tests as soon as new deprecation warnings are created in the library, they aren't passed on to users who then have to report them back in issues like #1195, saving everyone some time, effort, and noise.
There are no warnings at current so the tests don't fail. To check I reverted the code changes from commit e855fcf, ran Django 3.1 tests, and saw the warnings fail the test run at import time:
```
GLOB sdist-make: /.../django-import-export/setup.py
py38-django31-tablibstable inst-nodeps: /.../django-import-export/.tox/.tmp/package/1/django-import-expor …
```
=> Make tests fail on warnings

docs/changelog.rst, docs/installation.rst, import_export/admin.py, import_export/resources.py, tests/core/tests/test_resources.py
Fixes #1174. I've increased the default chunk size from 1 to 100, which should increase performance for most use cases.
Whilst doing this, I noticed that settings were being accessed at import times. This is not a recommended approach - settings are somewhat-mutable through tools like [`@override_settings`](https://docs.djangoproject.com/en/3.0/topics/testing/tools/#django.test.override_settings) so should only be read off the settings object. To this end, I've pushed all settings reads down into the functions that need them. This has had the beneficial side effect that the class-level `tmp_storage_class` attribute can also be a string to import, which might help prevent certain import loops.
I then rewrote the settings documentation. Mostly I aimed to standardize and clarify the …
=> Increase default chunk size to 100

setup.py
**Problem**
Fast access to docs and changelog.
**Solution**
These appear on the sidebar and provide neat, somewhat standard shortcuts to useful places. cf. [scout-apm](https://pypi.org/project/scout-apm/) , as defined in https://github.com/scoutapp/scout_apm_python/blob/631f2432f643d256ad5ab7ff6b8f7b95b14231f5/setup.py#L44
Ran `python setup.py check`.
=> Add documentation and changelog links on PyPI

import_export/formats/base_formats.py, import_export/resources.py, import_export/results.py, import_export/templatetags/import_export_tags.py, setup.cfg, tests/bulk/import_book.py, tests/core/migrations/0001_initial.py, tests/core/migrations/0005_addparentchild.py, tests/core/migrations/0007_auto_20180628_0411.py, tests/core/tests/test_admin_integration.py, tests/core/tests/test_base_formats.py, tests/core/tests/test_instance_loaders.py, tests/core/tests/test_mixins.py, tests/core/tests/test_resources.py, tests/core/tests/test_widgets.py, tests/urls.py
**Problem + Solution**
isort 5 added built-in configuration profiles: https://pycqa.github.io/isort/docs/configuration/profiles/ . The "black" format is compatible with the [black formatter](https://github.com/psf/black), which is becoming the "de facto" code formatting style for Python, and will be adopted by Django per [DEP 8](https://github.com/django/deps/blob/master/accepted/0008-black.rst), once Black is no longer beta software.
Adopting the same style here helps with consistency and comprehensibility for contributors. I was a little confused by the existing config that sorted `tablib` with standard library packages, since it's not from there.
`tox -e isort` passes with new configuration.
=> Run isort with "black" profile

AUTHORS, import_export/instance_loaders.py, tests/core/tests/test_instance_loaders.py
**Problem**
CachedInstanceLoader tries to clean the import_id field, even when it is not present in the inbound dataset, resulting in a KeyError thrown in fields.py. When using ModelInstanceLoader, an absent import_id column is allowed and results in the entries all being new, which is (to my mind) the most desirable behavior. 
**Solution**
Refactor CachedInstanceLoader to initialize with an empty cache when it gets a dataset without the import_id column. get_instance is then never called by the Resource since it checks whether the import_id_fields are present in the inbound dataset before calling get_instance.
Added a unit test which demonstrates the KeyError in the previous code and shows the correct initialization of CachedInstanceLoader in the new code. …
=> CachedInstanceLoader defaults to empty when import_id is missing

.travis.yml, setup.py, tox.ini
**Problem**
EOL python 3.5
https://devguide.python.org/devcycle/#end-of-life-branches
**Solution**
Remove it from Travis
=> Remove EOL Python 3.5 from CI

AUTHORS, import_export/locale/fa/LC_MESSAGES/django.po
Signed-off-by: Yazdan Ranjbar <Yazdan_ra@icloud.com>
Farsi translated messages in the locale
I added Persian/Farsi locale package
I've just added a `django.po` file that contains translated messages.
Have you written tests? Have you included screenshots of your changes if applicable? There is no need for that
Did you document your changes? There is no need for that
=> Add Farsi translated messages in the locale

.travis.yml, docs/changelog.rst, import_export/resources.py, requirements/test.txt, setup.py, tests/settings.py, tox.ini
* Add to tox and travis grids
* Set `DEFAULT_AUTO_FIELD` setting to avoid checks warnings.
* Update `ModelResource` to support `BigAutoField` and `SmallAutoField` correctly.
* Update setup.py to declare PyPI classifier.
=> Support Django 3.2

.travis.yml, tox.ini
**Problem**
Travis is trying to run tests using python36,37 against Django main, which only supports python38,39
**Solution**
Exclude from matrix
Tests should pass now
=> Don't test Django main branch using python36,37

.travis.yml, import_export/resources.py, tests/core/tests/test_resources.py
The Postgresql JSONField is deprecated since Django 3.1 and will be removed in Django 4.0:
https://docs.djangoproject.com/en/dev/releases/3.1/#postgresql-jsonfield
**Problem**
Import export not working with Django main
**Solution**
Change imports to new JSONField, remaining compatible with old Django versions.
All tests passing now.
=> Better support for Django main

import_export/resources.py, import_export/utils.py, tests/core/tests/test_resources.py
**Problem**
Fixes #1137 
**Solution**
Based on #1226
Uses Django's DB router as a fallback to decide which DB connection to use.
Added tests
=> Suport multiple databases

import_export/widgets.py
- Fix wrong function name `before_row_import` to 
`before_import_row` in BooleanWidget's example
https://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.BooleanWidget
=> Fix example in BooleanWidget docs

import_export/admin.py, import_export/mixins.py, tests/core/tests/test_admin_integration.py, tests/core/tests/test_mixins.py
**Problem**
- A [bug](#1268) where args and kwargs are not passed to `get_export_resource_kwargs()`
- Removed code duplication in `admin.py` and `mixins.py`
**Solution**
When looking into this issue, I noticed that we have a fair amount of code duplication in mixins.py and admin.py.
I removed the duplication as part of this fix.
I tried to keep code changes to a minimum, and also not to affect the public API defined in mixins.
I added some tests to improve the coverage in this area.
Would appreciate a code review from @manelclos and @ZuluPro
[Related comments](https://github.com/django-import-export/django-import-export/pull/692#issuecomment-359684319) by @manelclos 
> base mixin for import and base mixin for export, reused in the ViewMixin and the Admin Mixin, share code as much as …
=> Remove code duplication from mixins.py and admin.py

import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
There is a minor bug in `DateWidget` and `DateTimeWidget` where dates with years < 1000 are not formatted with 4 digits.
This is a minor issue but is a bug that may affect anyone exporting data with historic dates.
```python
>>> from import_export.widgets import DateWidget
>>> from datetime import date
>>> w = DateWidget()
>>> d = date(1000, 5, 3)
>>> w.render(d)
'1000-05-03'
```
```python
>>> d = date(999, 5, 3)
>>> w.render(d)
'999-05-03'
```
```python
>>> d = date(999, 5, 3)
>>> w.render(d)
'0999-05-03'
```
**Solution**
This PR fixes that by using the [`datetime_safe`](https://fossies.org/linux/Django/django/utils/datetime_safe.py) module in Django
There was an [earlier fix](https://github.com/django-import-export/django-import-export/pull/94/files) to address dates before …
=> Fix minor date formatting issue for date with years < 1000

import_export/admin.py, import_export/mixins.py
Further simplify `get_export_filename`.
@matthewhegarty this is what I meant here: https://github.com/django-import-export/django-import-export/pull/1277/files#diff-4faa8df298a05dc4474064942a1f01c316b6501091d1a4baa3095b3b1435cfa5R64
Tests are passing.
=> Simplify get_export_filename

import_export/admin.py, requirements/test.txt, tests/core/tests/test_admin_integration.py, tox.ini
**Problem**
The admin.py class has a `to_encoding` attribute, but it is not used (see #1305).  There was a PR (#245) for this but it was reverted in commit d331cb56.
**Solution**
A new kwarg is added to `get_export_data()` so that the encoding attribute can be passed.  By default `to_encoding` is None, meaning that there is no op and export data defaults to 'utf-8'.  If `to_encoding` is set, then export data is called with `encode()`.
- New unit and integration tests have been added.
- Tested manual exports from Admin console.
=> added support for 'to_encoding' attribute

.github/workflows/django-import-export-ci.yml, import_export/mixins.py, tests/core/tests/test_mixins.py
**Problem**
[This commit](https://github.com/django-import-export/django-import-export/commit/e1873a931367299d95863ab3dfabf1bb4dedf1af) produced a regression in one of my applications. The method `get_resource_class` is no longer called on the `ModelAdmin`.
**Solution**
Use original code, `self` was changed for `super()` in the refactor.
Local testing only. Will add tests if the change makes sense.
=> fix get_import_resource_class refactor

AUTHORS, import_export/widgets.py, tests/core/tests/test_widgets.py
Fixes #1313 
Was receiving "Enter a valid time" errors for time fields because tablib is already parsing these fields into python datetime objects, then it tries to convert them again in the clean method. This was already done with same method for the DateWidget and DateTimeWidget classes.
I did not test the change on the DurationWidget. I assume it will have the same issue, but I've never used timedelta fields before.
=> Fixes: (xls/xlsx) Time fields rejected on import even though they are valid

import_export/static/import_export/import.css
**Problem**
If the browser is switched to 'dark mode', then the confirm import page does not render correctly (reported in #1318).
**Solution**
Updated import.css to override colors using the 'prefers-color-scheme: dark' media query.
Colors were chosen by finding the [inverse](https://pinetools.com/invert-color) of the existing color.
- manually tested import using browser light and dark mode
- checked the existing admin site to confirm that it renders correctly in dark mode.
=> updated import.css to support dark mode (#1318)

import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
If the [forbiddenfruit](https://github.com/clarete/forbiddenfruit) library is installed, then crashes are seen at object instantiation.
The cause is that when forbiddenfruit is installed, calling [`dir()` on a null object](https://github.com/django-import-export/django-import-export/blob/89e52409787b36ea1f03e8eab2bfa68dc58e8a63/import_export/resources.py#L183) returns additional properties.  The logic attempts to get these properties from a null `options` reference, which causes the crash:
```
'NoneType' object has no attribute 'attrs' 
```
#1163 
**Solution**
This fix adds a check that `options` is not None.
- Ran tests with `forbiddenfruit` installed
- A test which simulates the problem is included.
- Have tested Admin console manually.
=> added guard for null 'options' to fix crash (#1163)

docs/installation.rst, tests/core/migrations/0004_bookwithchapters.py
**Problem**
If the example app is installed from scratch and the test.txt requirements file has not been installed, then there is a crash when `./manage.py migrate` is run.  (see #1125).  Although users should install the test dependencies, it's not clear that they should do this.  There might be cases where they don't want or need to install test dependencies.
**Solution**
- Adding an extra dummy field prevents the crash (thanks to josx)
- Updated the documentation to clarify that `test.txt` needs to be installed.
- No tests - code changes the test app migration
- I reproduced the issue (detailed in #1125) and proved that it is resolved with this patch.
=> (example app) fix crash on migrate when test dependencies not installed (issue 1125)

docs/changelog.rst, docs/conf.py, import_export/resources.py, import_export/results.py, requirements/test.txt, tests/core/exports/books-for-delete.csv, tests/core/tests/test_admin_integration.py, tests/core/tests/test_results.py
**Problem**
I have verified that there is a crash if one tries to delete records using the admin site (see #432).
**Solution**
The fix is simple - to add instance attributes to the `RowResult`.  
This introduced some code duplication, so I added a minor refactor of `RowResult` to set attributes via a new method.
- I also fixed sort order for `conf.py` attributes (raised by `make lint`).
- I added the `pytz` dependency which is needed for testing with python 3.9 (see #1336).
- Added test file `books-for-delete.csv`
- Integration test to prove the issue exists and is fixed (`test_admin_integration.py`)
- Added unit tests for the new `RowResult` method
=> Fix for crash when deleting via admin site

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_resources.py, tests/core/tests/test_widgets.py
Using interger widget with big interger generate overflow. check #788 
Change the use of `float` with `decimal` (more precision) in interget widget
Have you written tests?
- Create a new testing it
- I have changed tests to match decimal use.
=> Big integer support for Integer widget (#788)

docs/changelog.rst, docs/getting_started.rst
**Problem**
Issue #778.  If one follows the documentation it can lead to a crash when trying to import a book with no author name.
This change fixes that error.
**Solution**
Updated the documentation so that the example gracefully handles book imports when there is no author name.
- No tests required
- Built documentation locally and verified the change is correct.
=> Documentation: correct error in example application which leads to crash

.github/workflows/django-import-export-ci.yml, docs/changelog.rst
**Problem**
A minor improvement to the CI script.
The CI script was using a hard-coded password which is not ideal.  Best practice is to use a secret defined in Github.
**Solution**
The CI script now uses a Github secret instead of a hard-coded password.
Verified that the CI process ran ok, meaning the change is valid.
=> Use Github secret in CI script instead of hard-coded password

.github/workflows/django-import-export-ci.yml, docs/changelog.rst, setup.py, tox.ini
**Problem**
Now that [python 3.10](https://docs.python.org/3.10/whatsnew/3.10.html) is available, I have added it to the list of supported python releases.
Whilst testing this, I noticed tox failures for >= 3.9 only, because support for pytz was dropped in that release.  However, since pytz is still a dependency for Django, I added it to the import list in `test.txt`, since it is required for `test_widgets.py`.
**Solution**
- Updated files to reference python 3.10.
Ran full tox run through locally.
=> Added python3.10 to tox environment list

docs/changelog.rst, tests/bulk/README.md, tests/settings.py
**Problem**
Whilst testing #1329, I added `django_extensions` to `settings.py` so that the `runscript` command could be used during bulk testing.  However, this causes a crash (see issue #1355) if the `test.txt` dependencies are not used.
**Solution**
1. Removed `django_extensions` from settings.
2. Updated bulk testing readme.md to clarify that this needs to be installed if testing.
- Tested locally in a new virtualenv.
- No new tests necessary.  
- Ran the existing test suite.
=> Removed `django_extensions` from example app settings.

docs/changelog.rst, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
Issue #1270 
No tests broke. Specific tests pending based on acceptance of the change.
=> Use future value of ManyToManyField to check if value would change

docs/changelog.rst, docs/getting_started.rst, import_export/admin.py, import_export/forms.py, import_export/mixins.py, import_export/resources.py, import_export/templates/admin/import_export/import.html, tests/core/admin.py, tests/core/tests/test_admin_integration.py, tests/core/tests/test_forms.py, tests/core/tests/test_mixins.py, tests/core/tests/test_resources.py
**Problem**
Issue #765
**Solution**
If the resource classes in ModelAdmin are provided as list i.e.:
```python
class InvoiceAdmin(ModelAdmin):
resource_class = [InvoiceResource, AccountingInvoiceResource]
```
Then there will be additional field in the ExportForm asking user to choose the resource:
The displayed name of the resource can be set by `ModelResource.name` or `ModelResource.get_display_name()`.
I didn't write the documentation or tests yet, but I am willing to, but I would like some opinions on my approach first.
=> add option to have multiple resource classes in ModelAdmin

.github/workflows/django-import-export-ci.yml, docs/changelog.rst, import_export/__init__.py, import_export/admin.py, import_export/resources.py, requirements/base.txt, setup.py, tests/core/tests/test_resources.py, tests/settings.py, tox.ini
**Problem**
**This is for inclusion into Release 3**
Drops support for the following which are at EOL.
- python 3.6
- django 2.2, 3.0, 3.1
- Remove skipped test 
- I checked the history of this test and could not confirm that it was serving any useful purpose, so decided to remove.
- Removed import of `JSONField` from `django.contrib.postgres.fields` because this is included in Django since 3.1
Planned for inclusion in 3.0 release
=> Drop support for django EOL versions

AUTHORS, docs/changelog.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
**Problem**
https://github.com/django-import-export/django-import-export/issues/1373
This is the PR for this issue.
When there is only one `formats` like the code below,the format on the Export action does not display  `---`.
By default, you can select the contents specified in formats.
```python
from import_export.admin import ExportActionModelAdmin
from import_export.formats import base_formats
class CategoryAdmin(ExportActionModelAdmin):
formats = [base_formats.CSV]
```
**Solution**
In the `ExportActionMixin` constructor of `import_export/admin.py`, if the size of `formats` exceeds 1, add `---` to choices.
- After modifying `CategoryAdmin` in `tests/core/admin.py` as follows, I confirmed that the format of the Export action in the admin screen is csv.
- I added …
=> Default format selections on export action

docs/changelog.rst, import_export/results.py, tests/core/tests/test_resources.py, tests/core/tests/test_results.py
**Problem**
`import_data()` crashes when passed an empty dataset and `collect_failed_rows` is True.
See #1380 
**Solution**
Add check for `headers is None` and create empty list if so.
- Added unit tests.
=> Fix crash on `import_data(Dataset(), collect_failed_rows=True)`

.github/workflows/django-import-export-ci.yml, docs/changelog.rst, import_export/__init__.py, import_export/admin.py, import_export/resources.py, requirements/base.txt, setup.py, tests/core/tests/test_resources.py, tests/settings.py, tox.ini
**Problem**
Drops support for the following which are past EOL.  This was reviewed in #1366 for inclusion in 3.0 release.  This release pushes it into the main repo for inclusion in 2.8.0.
- python 3.6
- django 2.2, 3.0, 3.1
- Remove skipped test 
- I checked the history of this test and could not confirm that it was serving any useful purpose, so decided to remove.
- Removed import of `JSONField` from `django.contrib.postgres.fields` because this is included in Django since 3.1
=> Drop support for EOL dependencies

AUTHORS, docs/changelog.rst, import_export/admin.py, tests/core/tests/test_mixins.py
**Problem**
You can see how hard it is to use the custom export form. You have to override the whole [export_action()](https://github.com/django-import-export/django-import-export/blob/26977ed44ff8f2c9769b14bc69f0b41f3524da6d/import_export/admin.py#L403) method.
https://stackoverflow.com/a/67653671/17465982 referes to this problem as well
**Solution**
Introduced the get_export_form() method on ExportMixin as an analogue to [get_import_form()](https://github.com/django-import-export/django-import-export/blob/26977ed44ff8f2c9769b14bc69f0b41f3524da6d/import_export/admin.py#L177) from ImportMixin
Did you document your …
=> Feat add get export form to export mixin

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
Method definitions are defined incorrectly in `widgets.py`.  See #1412.
**Solution**
Change the interface for `clean()` to remove the unused `args` param.
```python 
def clean(self, value, row=None, *args, **kwargs):
def clean(self, value, row=None, **kwargs):
```
Also, changed the constructors for `ForeignKeyWidget` / `ManyToManyWidget`.
- Ran test suite.
- Described breaking changes in changelog.
=> Fix widgets incorrect method definitions

docs/changelog.rst, import_export/resources.py, import_export/widgets.py, tests/core/tests/test_resources.py, tests/core/tests/test_widgets.py
**Problem**
`CharWidget` did not appear in `resources.WIDGET_MAP` - this is not an issue because the functionality of `CharWidget` is equivalent to `Widget`.  However this does mean that there is a redundant method in `CharWidget` which I have removed.
**Solution**
- Updated `WIDGETS_MAP` to return `CharWidget` for `CharField` for consistency.
- Removed redundant method `render()` from `CharWidget` (it is equivalent to the `Widget` method)
- Added tests
=> CharWidget optimisations

docs/changelog.rst, requirements/base.txt, setup.py, tests/core/tests/test_admin_integration.py
**Problem**
#1397 Imports fail when CacheStorage is enabled and the file contains LF char.
**Solution**
This was an issue in tablib which was fixed in release 3.2.1.
This means that django-import-now requires tablib 3.2.1 as a minimum dependency.
- Integration tests are included which verifies the fix.
- Manually tested steps to reproduce from issue
=> Fix failure when CacheStorage enabled and file contains LF char

docs/getting_started.rst, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
The use natural foreign key capability on foreign key widgets has to be enabled per widget
**Solution**
I added a ResourceOptions setting to allow detecting models that can use natural foreign keys. It defaults to False.
There are tests for the utility function (has_natural_foreign_keys) and all the execution paths of the Resource setting
-setting off, model has natural foreign key functions -> not used
-setting on, model does not have foreign key functions -> not used
-setting on, model has foreign key functions -> used
=> Auto detect natural foreign key setting for widgets at the resource level

.github/workflows/django-import-export-ci.yml, docs/changelog.rst, runtests.py, tests/core/tests/test_admin_integration.py, tox.ini
**Problem**
Fixes issue #1424 
Coverage files and 'response.html' get generated when running locally
**Solution**
- Removed the unused write to `response.html`
- Added an Env var which gets set in CI only, and which indicates that coverage data should be generated.
- Added a new script `runtests.py` which adds the `COVERAGE` env var if present
- Tested locally
- Tested in CI
=> Remove unnecessary files generated when running tox locally

docs/getting_started.rst
=> fix get_resource_class reference in documentation

docs/changelog.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
Fix for #1432
Avoid crashing and print a warning about what needs to be changed to get it fully working in 3.0
=> [3.0] Improve import form compatibility

docs/changelog.rst, tests/settings.py
**Problem**
Fixes #1449.  This affects the example application only.
There is a form template in the test app (`category_list.html`).  This uses a `{{ form }}` tag.  For django 4.1 this means that there has to be a [declaration of the form renderer to use](https://docs.djangoproject.com/en/dev/releases/4.1/#forms-4-1). 
**Solution**
This change adds a conditional FormRenderer to test settings when the Django version is 4.1.
- Ran unit tests
- Manually checked the HTML rendering of http://localhost:8000/export/category/ before and after the addition of the setting.  The form still renders ok.
[form_after.html.txt](https://github.com/django-import-export/django-import-export/files/8888964/form_after.html.txt) …
=> Fix deprecation: Added support for transitional form renderer

AUTHORS, docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
...rather than strings
Fix #1165
=> Apply make_aware when the original file contains actual datetimes

docs/changelog.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
As per Django's documentation
> Clearly, user-submitted data shouldn’t be trusted blindly and inserted
> directly into your web pages, because a malicious user could use this kind of
> hole to do potentially bad things. This type of security exploit is called a
> Cross Site Scripting (XSS) attack.
> To avoid this problem, you have two options:
>
> * One, you can make sure to run each untrusted variable through the escape
>   filter (documented below), which converts potentially harmful HTML characters
>   to unharmful ones.
=> Escape HTML output

AUTHORS, docs/changelog.rst, import_export/admin.py, import_export/forms.py, import_export/static/import_export/guess_format.js, import_export/templates/admin/import_export/import.html, tests/core/tests/test_admin_integration.py
**Problem**
In the Django-admin, a small piece of JavaScript looks to the file extension of the file uploaded, and select the format, given the format for that extension occurs in the dropdown.
**Solution**
A JavaScript file `guess_format.js` hooks an event handler on the file input element. In case the file changes, it obtains the file extension and starts looking for that extension in the dropdown. In case it finds that extension, it picks that format.
Have you written tests? No, this is frontend.
Have you included screenshots of your changes if applicable? below two images. After selecting the `file.csv`, the format automatically changes to `csv`.
=> Autodetect the format through the extension

AUTHORS, docs/changelog.rst, import_export/admin.py, import_export/templates/admin/import_export/change_list.html, tests/core/admin.py, tests/core/templates/core/admin/change_list.html, tests/core/tests/test_admin_integration.py
**Problem**
The mixins for the admin integration override the admin `change_list_template`. This means that any customization of that template done by the user is effectively ignored. This also means that `django-export-import` is not compatible with mixins from other libraries that customize the object tools in the change list view (e.g., `django-admin-sortable2` or `reversion`).
This issue was reported in #1450
**Solution**
This makes the `change_list_template` extend whatever customized template is already present in the class hierarchy. This solution is loosely based on the [solution to the same issue in django-admin-sortable2](https://github.com/jrief/django-admin-sortable2/pull/317).
Additional assertions in admin integration tests cover this use case.
=> Allow custom change_list_template in admin views using mixins

import_export/forms.py, tests/core/tests/test_admin_integration.py
**Problem**
Minor refactoring of `Media` declaration from #1460 for easier testing.
**Solution**
Moved `Media` class declaration to [dynamic](https://docs.djangoproject.com/en/4.1/topics/forms/media/#media-as-a-dynamic-property) declaration.
- Added integration tests
- Tested manually with example app with both DEBUG on / off
=> refactored forms 'media' declaration for easier testing

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
Following #1478, DateTimeWidget.clean() will raise `ValueError` when passed a tz aware datetime.  This is because `make_aware()` raises an error if the date already has tz info.
**Solution**
See changes.
- Added test
- Tested with my external app
=> bugfix: `DateTimeWidget.clean()` handles tz aware datetime

.github/workflows/django-import-export-ci.yml, docs/changelog.rst, setup.py, tox.ini
**Problem**
Python 3.11 is released.
> [Django 4.1 will be the first version to support Python 3.11](https://code.djangoproject.com/ticket/33173)
**Solution**
Update tox, `setup.py`, CI script to support python 3.11
- Updated tox and tested locally by running `./runtests.sh`
=> support python 3.11

AUTHORS, docs/changelog.rst, import_export/admin.py
**Problem**
To be honest, this is not exactly a problem, as long as you don't heavily modify Django admin and write classes inheriting from ``ExportMixin``. Since some time Django has a special utility function for getting ``list_select_related``, which is called ``get_list_select_related`` and it should be used to override some settings. 
In my application I used it to implement dynamic Django admin columns (https://github.com/iplweb/bpp/blob/dev/src/dynamic_columns/mixins.py#L8) and it occurred, that ``ExportMixin`` (that I also use, that's a quite big project) doesn't play nicely with it, so well, here I am. 
**Solution**
All this needs is to analogically call to ``get_*``, just like we already do in ``get_list_display`` and such. 
No additional tests, Django …
=> Use get_list_select_related (fix #1493)

AUTHORS, docs/changelog.rst, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
The RowResults in the case of skipped rows during import do not include the skipped instance's information.
There are several use-cases when the primary keys of the imported rows are needed. These use-cases usually include hooks that are running alongside the import but have no access to the Resource class or are isolated/separated or even the caller method which invokes the import process in code. 
**Solution**
Invoked the `add_instance_info` method in both cases of new/udpated rows and skipped ones.
Did you document your changes? 
After the change the reported RowResult includes instance information:
=> feat: report skipped rows properly - including the instance info

import_export/widgets.py
`widgets.DateWidget` and `widgets.TimeWidget` both takes additional `format` parameters but they don't have docstrings on default behavior like on `widgets.DateTimeWidget`
=> add detailed format parameter doctsrings to DateWidget and TimeWidget

AUTHORS, import_export/exceptions.py, import_export/fields.py, import_export/resources.py, import_export/widgets.py, tests/core/tests/test_fields.py, tests/core/tests/test_resources.py
**Problem**
Defining custom methods for dehydration of the field
I have had situations where I had to dynamically generate new fields during export. In this case I wasn't able to pre-define dehydration methods in `ModelResource` so I added `dehydrate_method` parameter to `Field` which solved this issue.
**Solution**
I have added `dehydrate_method` parameter to `fields.Field` so custom methods 
I have written tests.
Did you document your changes? 
Added docstrings.
Let me know if anything needs to be changed!
=> Add field optional dehydrate method param

AUTHORS, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
When transactions are supported, import_data_inner will create a subtransaction for each row.
In bulk mode, no db operations are made anyway so there's no need to for the extra db queries of creating and releasing a save point.
**Solution**
Do not create save point for each row when bulk mode is enabled.
Sample bulk_import results (on postgres):
**before the changes:**
do_create()
Time   6.004
Memory 2.21875
Max 82.12890625 Min 79.91015625
do_update()
Time   5.205
Memory 3.9375
Max 103.12890625 Min 99.19140625
do_delete()
Time   3.548
Memory 0.01171875
Max 105.78125 Min 105.76953125
**after the changes:**
do_create()
Time   2.2
Memory 2.890625
Max 79.8125 Min 76.921875
do_update()
Time   1.616
Memory 7.921875
Max 101.4609375 Min 93.5390625
do_delete() …
=> Improve bulk import performance

docs/bulk_import.rst, import_export/resources.py, tests/core/tests/test_resources.py
**Problem**
Errors during bulk operations are not returned to the user in dry_run mode. Instead the exception is caught and logged and user can proceed to real import (which fails).
An extra savepoint is also used to rollback the transaction on dry_run/errors, but we can used the current transaction block instead to achieve the same.
**Solution**
Make errors raised during bulk operation part of result.base_errors so they can be returned to the user.
Remove extra savepoint.
Tests were written + documentation updated.
=> collect errors on bulk operations

import_export/resources.py, tests/scripts/bulk_import.py
This should make it for the slight memory increase of #1541 :)
**Problem**
Dataset is loaded twice in memory during import process because of dataset.dict
**Solution**
Use the dataset in memory.
Test ran on importing 1000000 rows
**before the changes**
do_create()
Time   101.9
Memory 565.85546875
Max used 1230.79296875
**after the changes**
do_create()
Time   97.75
Memory 84.62890625
Max used 746.43359375
=> reduce memory footprint during import

AUTHORS, docs/installation.rst, import_export/admin.py, import_export/formats/base_formats.py, import_export/mixins.py, tests/core/tests/test_base_formats.py
**Problem**
HTML Export did not sanitize the output, resulting in a potential XSS attack. (reported: https://github.com/django-import-export/django-import-export/issues/1547)
Consider the following scenario:
* There's an users table,
* A user changes his name to a malicious string (like `<script>alert('hello')</script>`), 
* An admin triggers an export of the users table
* An admin views the export, the javascript code gets executed in his browser
This is especially risky if there's an in-place viewer for the HTML reports in django admin, under the same domain as the app.
**Solution**
I modified the HTML format to go through every cell of the export and run `html.escape` on it. 
I figured out that `export_data` would be the correct place to do it, since this is the last method that gets …
=> Fix xss in html export

AUTHORS, import_export/resources.py, tests/core/tests/test_resources.py
Problem
When importing a resource for a new instance with a many-to-many relation and non-filled fields have been evaluated for differences before the many-to-many field, an error occurs when attempting to retrieve the list of related entities from the original entity to get the differences. This happens because Django returns None when trying to retrieve a related manager for a model with a None primary key.
The specific error message is: `AttributeError: 'NoneType' object has no attribute 'all'. `in  File /venv/lib/python3.9/site-packages/import_export/resources.py", line 630, in skip_row
For more information, you can refer to issue 1558
https://github.com/django-import-export/django-import-export/issues/1558
Solution
The solution is to modify the code to not try to retrieve the list of …
=> Prevent error comparing m2m field of the new objects (#1558)

README.rst, RELEASE.md, docs/advanced_usage.rst
**Problem**
It's not clear how to pass data from a custom form to the Resource.  (e.g. #1553).
**Solution**
Updated the 'advanced usage' documentation to give an example.
Tested by building docs locally and checking.
=> Add documentation for passing data from admin form to Resource 

docs/faq.rst, security.md
**Problem**
Added documentation to FAQ to clarify workaround for `RelatedObjectDoesNotExist` exception (see #1556).
**Solution**
FAQ entry
N/A
=> updated FAQ to include workaround for `RelatedObjectDoesNotExist` exception

import_export/formats/base_formats.py
import_set excepts kwargs arguments that are currently not passed
**Problem**
The create_dataset function receives kwargs parameters but does not pass them along when calling import_set from tablib.
This results in some issues such as custom delimiters not being acknowledged during the import process.
The solution proposed in #181 used to work but does not anymore after upgrading to the latest version of the framework.
**Solution**
Now passing the kwargs when calling the import_set function
=> Pass kwargs to import_set function

.editorconfig, .github/workflows/django-import-export-ci.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, Makefile, docs/contributing.rst, docs/faq.rst, requirements/test.txt, setup.cfg, setup.py, tox.ini
**Problem**
We have a long-standing issue in that we don't follow best practices by not having automatic linting / formatting.  This PR adds rules to apply black formatting and flake8 checks.
**Solution**
- Added `.pre-commit-config.yaml` to include rules for formatting using black, flake8 and isort
- values such as line length of 88 are [black defaults](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#)  
- I matched [Django formatting for flake8](https://github.com/django/django/blob/53aee470d5b35e2708864d5221d2b5655e10c091/setup.cfg#L56)
- I will enable auto formatting on PRs after the global reformat has been applied.
- pre-commit checks should automatically be run for PRs using [pre-commit.ci](https://pre-commit.ci)
- removed isort from tox:  it is now …
=> Add automatic formatting and linting

docs/advanced_usage.rst, docs/api_results.rst, docs/changelog.rst, import_export/resources.py, import_export/results.py, tests/core/tests/test_resources.py
**Problem**
#1583.  It was previously not possible to add workflow if incoming values change.
**Solution**
- <s>The row dict is passed into `after_import_instance()` as a kwarg (meaning it will be backwards compatible).</s>
- <s>I added `original` to `after_import_row()`</s>
- <s>I think this is cleaner because it means the comparison can take place after the instance has been successfully persisted.</s>
- <s>We can use the instantiated `original` instance instead of checking values in `row`.</s>
- I settled on adding `original` and `instance` to `RowResult`
-  I feel this is cleaner
- It will potentially increase memory usage for large imports, but this can be mitigated with `skip_diff`. 
- Added new `store_instance` option so that users can opt-in to this feature …
=> add `original` and `instance` objects to `RowResult`

docs/changelog.rst, tox.ini
**Problem**
The CI breaks due to a change in the HTML parser used in tablib dev (issue #1602).
This should be a temporary change until the issue with tablib is resolved (raised [here](https://github.com/jazzband/tablib/pull/554#issuecomment-1642347066))
**Solution**
Removed tablib main from tox
Tests should pass
=> Fixed tox build by removing reference to tablib dev

AUTHORS, docs/changelog.rst, import_export/locale/ru/LC_MESSAGES/django.po
A space was added after the comma: ...импорт', если...
There was no space after the comma in the translation.
Added a space
Just added a space after the comma in the translation
=> A space was added after the comma

AUTHORS, docs/advanced_usage.rst, docs/installation.rst, import_export/admin.py, import_export/mixins.py, tests/core/tests/test_admin_integration.py, tests/core/tests/test_mixins.py
**Problem**
XLS is becoming obsolete and is introducing problems such as #1592 and #1601
**Solution**
Having settings that can be used by developers to specify what formats one wants to be available to end users who know nothing about such errors.
Yes I have added tests and documented my changes
Settings
Import Formats Available
Export Formats Available
Export Action Formats Available
=> Include allowed formats settings

docs/advanced_usage.rst, docs/changelog.rst, docs/faq.rst, docs/installation.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
**Problem**
We've had a few issues related to interoperability with 3rd party libraries.  Rather than trying to patch this, I suggest that documenting workarounds is the best solution for now.
**Solution**
Updated Admin UI docs and FAQ.
- unit tests
- reviewed docs locally
=> updated Admin docs to include guidance on third party interoperability

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
Issue #1573.
This adds options to force CharWidget to return its values as strings.  This seems logical because the other widgets use `clean()` to return their values as underlying types.
However, this could break existing implementations, so I have preserved the current default behaviour, and made it optional to return values as strings, also handling the 'null' case either as empty string or as `None`.
Maybe we will make this mandatory behaviour of CharWidget in a future release.
**Solution**
- Updated constructor to accept kwargs
- Modified clean()
Full unit tests added.
=> Enable CharWidget to return string

.readthedocs.yaml, RELEASE.md, docs/changelog.rst
**Problem**
- Readthedocs build failing due to python version
- [Deprecation warning](https://blog.readthedocs.com/use-build-os-config/)
**Solution**
Added .readthedocs.yaml
=> added readthedocs config

import_export/admin.py, import_export/templates/admin/import_export/change_list.html
**Problem**
This is partial fix for #1531
One of the problems is, that the `base_change_list_template` clashes with variable of same name used in `django-adminsortable2`.
**Solution**
I renamed the variable to be specific to this project.
Not sure if tests are needed and how they should work.
=> fix cooperation with adminsortable2 (workaround needed)

import_export/templates/admin/import_export/change_list.html, tests/core/tests/test_admin_integration.py
**Problem**
The django-compress raises following errors during run of `compress` management command:
```
Compressing... 
Error parsing template admin/import_export/change_list_import.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template admin/import_export/change_list_import_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template admin/import_export/change_list_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template admin/import_export/change_list.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
``` …
=> change_list.html: add default base_template value to fix django-compress

.github/workflows/test.yml, Makefile, docs/advanced_usage.rst, docs/changelog.rst, docs/installation.rst, import_export/admin.py, import_export/formats/base_formats.py, import_export/mixins.py, import_export/resources.py, pyproject.toml, requirements/base.txt, tests/core/tests/test_admin_integration.py, tests/core/tests/test_base_formats.py
**Problem**
The latest version of tablib supports HTML and Excel escaping, so removed the logic from our codebase.
**Solution**
Also, upgraded to latest version of tablib (i.e. master) so that HTML escaping is supported by default.
- Updated tests
=> Refactor to support latest escaping logic

docs/changelog.rst, import_export/resources.py, import_export/results.py
**Problem**
Closes #1586 
**Solution**
Removed unused var (deprecated in v3)
Integration tests
=> Removed unused ``new_record`` var

docs/api_widgets.rst, docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
`NumberWidget.render()` returns 'None' as string if value is None and `coerce to string` is set.
**Solution**
Add specific check for this
Test added.
=> `NumberWidget.render()` returns None as string

docs/changelog.rst, import_export/admin.py
**Problem**
Closes #1673 
This just ignores the deprecation for now.
(see #1674 for the complete fix which will go into v4)
**Solution**
Added deprecation warning so that tests pass in `main`
All tests pass.
=> Added deprecation warning for ``LogEntry``

docs/changelog.rst, import_export/admin.py, tests/core/admin.py, tests/core/tests/test_admin_integration.py
The method reference in get_actions within import_export/admin.py was updated from using ExportActionMixin.export_admin_action to type(self).export_admin_action. This change ensures that the function call always refers to the current instance's class method. This is particularly important in situations where the class has been inherited and the method overridden. Fixing #1680.
**Problem**
Subclassing `.export_admin_action` did not work: the old method was still triggered.
**Solution**
Allow subclassing `.export_admin_action` by using `type(self)` instead of `ExportActionMixin`.
=> Update method reference in get_actions

docs/changelog.rst, import_export/admin.py, import_export/templates/admin/import_export/export.html, import_export/templates/admin/import_export/import.html, import_export/templates/admin/import_export/resource_fields_list.html, tests/core/tests/test_admin_integration.py
=> show exported fields in admin

docs/changelog.rst, runtests.sh
Updated `docker-compose` command to docker compose V2 syntax which is `docker compose` without dash.
#1686
=> update docker-compose command to docker compose V2 syntax

docs/api_forms.rst, docs/changelog.rst, docs/contributing.rst, docs/release_notes.rst, import_export/admin.py, import_export/forms.py, import_export/mixins.py, import_export/templates/admin/import_export/import.html, tests/core/exports/authors.csv, tests/core/tests/admin_integration/mixins.py, tests/core/tests/admin_integration/test_action.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_forms.py, tests/core/tests/test_mixins.py, tests/core/tests/test_permissions.py
**Problem**
Closes #1682
If only one file format is defined in `IMPORT_FORMATS`, then display a read only field:
settings.py:
```python
from import_export.formats.base_formats import CSV, XLSX
IMPORT_FORMATS = [CSV]
```
This makes the import process consistent with the export process.
**Solution**
Update the form to add extra logic to handle read-only fields.
Update the import.html template.
- Integration tests
=> Default to read only field on import if only one file format is defined

.github/workflows/test.yml, docs/changelog.rst, import_export/formats/base_formats.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/test_base_formats.py, tests/core/tests/test_widgets.py, tests/core/tests/utils.py, tox.ini
**Problem**
Handles deprecation warnings from python3.12
**Solution**
- Added catches for warnings where required.
- Integration test coverage
=> Handle python3.12 datetime utc deprecation

docs/advanced_usage.rst, docs/changelog.rst, docs/installation.rst, import_export/admin.py, import_export/tmp_storages.py, tests/core/admin.py, tests/core/tests/test_tmp_storages.py, tests/settings.py
**Problem**
Closes issue #1210 
**Solution**
Allows for configuration of a custom storage backend using existing Django config mechanisms
- Have added integration tests
- Have tested manually, including upload to s3 bucket using django-storages.
=> Customizable storage

AUTHORS, import_export/static/import_export/import.css
**Problem**
A rendering problem where the import staging table was not respecting the manual choice of color scheme.
Fixes https://github.com/django-import-export/django-import-export/issues/1718.
**Solution**
I duplicated the CSS rules and checked for `html[data-theme="light/dark"]`. The same thing is done in the Django source code for the admin module: https://github.com/django/django/blob/main/django/contrib/admin/static/admin/css/dark_mode.css
We can see with the CSS rules that the manual choice is overriding the preferred color scheme.
=> Respect color scheme override

docs/changelog.rst, docs/faq.rst
Updated FAQ docs (tested locally before pushing)
=> updated FAQ to add entry on skipping rows with validation errors

docs/changelog.rst, import_export/resources.py, import_export/widgets.py, tests/core/tests/test_resources/test_resources.py
**Problem**
#974
**Solution**
This is concept of a solution of the problem with unnecessary queries for IDs.
I would like to get some feedback on this. I am not sure about which other cases could this affect and whether we are able to fix more cases.
The current solution is mostly bypassing the logic of Widget and leaking it to the Fields. But I am not sure how to make this correctly, because the data in Widgets are not sufficient for this and also when the `Widget.render()` is called the demage is already done and the query is called.
It includes a clear test case scenario documenting the problem.
=> Fix for 974

docs/changelog.rst, docs/release_notes.rst, import_export/resources.py, tests/core/tests/test_resources/test_resources.py
**Problem**
Closes #1731 
Renamed methods were re-added with deprecation warnings to ease upgrades for users with direct method calls in their implementations.
**Solution**
Re-added original method names with call to new (and DeprecationWarning)
- Added integration tests
- Updated Release Notes
=> Re-add removed methods with deprecations for backwards compatibility

docs/admin_integration.rst, docs/changelog.rst, docs/faq.rst, docs/release_notes.rst, import_export/admin.py, import_export/templates/admin/import_export/import.html, tests/core/tests/admin_integration/test_import.py
**Problem**
Closes #1724 
**Solution**
Added a new `ImportMixin` attribute to control which elements are displayed.  Users can override this to customize the error display.
- Added integration tests
- Updated docs
=> Improve Admin UI import error messages

docs/changelog.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
**Problem**
Closes #1738 
**Solution**
Pass `get_export_resource_kwargs()` to Resource constructor to code block added in #1685.
- Added test
=> pass `get_export_resource_kwargs()` to Resource constructor

docs/changelog.rst, import_export/admin.py, tests/core/tests/test_admin_integration.py
**Problem**
Closes #1716
**Solution**
Passing the model class to the constructor is redundant.
- Added a test which proves the crash occurs if the fix is not in place.
=> Fix issue with model passed to Resource constructor crashes on export

docs/changelog.rst, import_export/mixins.py, tests/core/tests/test_admin_integration.py
**Problem**
Closes #1741 
**Solution**
Returned kwargs 
- Added tests
=> Return `kwargs` by default from `get_resource_kwargs`

AUTHORS, import_export/resources.py
Without the newline before the code block intersphinx isn't able to parse the docstring. I also adjusted the indentation of the block and propose to use the python environment for the code block.
**Problem**
[Intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) isn't able to parse the docstring for `skip_row` which is results in failing documentation builds.
Related issue: #1742 
**Solution**
I added a newline before the code block and optionally adjusted the indentation and code environment of the block.
=> Fix indentation for skip_row docstring

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
Closes #1736 
**Solution**
Add a check to widget render() before attempting to render a value.  This prevents a crash due to unknown type such as Now().
- Added unit tests
- Manual test using steps defined in original issue
Screen shots show different error when fix is in place:
=> Add check for type to widget render

docs/changelog.rst, import_export/admin.py, tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1723
**Solution**
Added except block to catch field error, and return message as error message.
Added integration test
=> Handle django FieldError raised during export

docs/changelog.rst, import_export/admin.py, tests/core/tests/admin_integration/test_import.py
**Problem**
Closes #1722 
**Solution**
Catch the `FieldError` exception and send the response as a message to the UI
Added integration test.
=> Handle `FieldError` during import via Admin UI

docs/changelog.rst, import_export/results.py, tests/core/tests/test_results.py
**Problem**
Closes #1763 
**Solution**
Add try / catch block to catch and log any exception which arises from trying to call `force_str()` on an object which is not serializable via a call to `__str__()`
- Includes test
=> added fix to `add_instance_info()` for unserializable instances

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
**Problem**
Closes #1769
**Solution**
Add check for None values and return value according to `coerce_to_string` param.
- Added unit tests
=> Fix SimpleArrayWidget render crash

import_export/formats/base_formats.py
It used to be overridden for Python 2 compat
=> Remove unneeded format method overrides

docs/changelog.rst, import_export/resources.py, tests/core/admin.py, tests/core/tests/admin_integration/mixins.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_resources/test_diffs.py
**Problem**
Closes #1784
**Solution**
- Fix `get_diff_headers` so that it matches the field order in the Diff class.
- Remove unnecessary method `get_user_visible_headers()`
- includes test
=> Fix for incorrect header order on 'confirm' page

import_export/templates/admin/import_export/import.html
Closes #838
**Problem**
More details in #838.
**Solution**
Right now seems like template is not following Open-Closed Principle and we need whole file to modify. With that block we can easily extend import template
=> feat(dj.admin import): Add additional django template block for extending

docs/changelog.rst, docs/release_notes.rst, import_export/admin.py, import_export/forms.py, import_export/mixins.py, tests/core/admin.py, tests/core/tests/admin_integration/test_action.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/resources.py, tests/core/tests/test_mixins.py
**Problem**
Closes #1778
- Standardise method args
- Also fixes issue where `get_import_data_kwargs()` did not return the kwargs that were passed.
**Solution**
- Standardise mixin method interface.
- Changes summarised in release_notes.rst
=> Support dynamic selection of Resource class based on request property

docs/changelog.rst, import_export/admin.py, tests/core/admin.py
**Problem**
- `form` param not passed to `get_import_resource_kwargs()` as it was previously
**Solution**
Passed the param.
Tested manually
=> Fix regression of `form` not being passed to `get_import_resource_kwargs()`

.github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, docs/changelog.rst, import_export/admin.py, pyproject.toml, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_widgets.py, tox.ini
**Problem**
Closes #1782
**Solution**
- Removed redundant checks and tests
- Ran tox
=> Remove support for django 3.2

docs/changelog.rst, import_export/resources.py, tests/core/tests/test_model_resource_fields_generate_widgets.py, tests/core/tests/test_resources/test_modelresource/test_widget.py
**Problem**
Closes #1804 
**Solution**
- Added code to search base classes for `Field` to identify if there is a valid widget mapping.
- added tests
=> Added fix for crash when `CharField` subclass is present

docs/changelog.rst, import_export/exceptions.py, import_export/resources.py, import_export/widgets.py, tests/core/tests/test_resources/test_natural_foreign_key.py, tests/core/tests/test_widgets.py
**Problem**
Closes #1816 
`key_is_id` which fixes #974 clashes with `use_natural_foreign_keys`.
**Solution**
Only apply the `key_is_id` widget kwarg is `use_natural_foreign_keys` is False.
Added tests (thanks to @mishka251)
=> fixed issue with `natural_foreign_keys` and `key_is_id`

docs/changelog.rst, import_export/resources.py, tests/core/tests/test_model_resource_fields_generate_widgets.py
**Problem**
Closes #1817 
If a project contains a custom FK field implementation, then this can crash on startup.
**Solution**
Added a missing code block to call the `get_fk_widget()` method.
- Added test
=> fix issue with widget assignment for custom ForeignKey subclasses

docs/admin_integration.rst, docs/changelog.rst, import_export/admin.py, import_export/templates/admin/import_export/export.html, tests/core/admin.py, tests/core/tests/admin_integration/test_action_export.py, tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1806 
A 'SELECT * FROM table' was executed on every export.  Refactored to perform this only when necessary
**Solution**
- Restrict select of valid items only to cases of export from ['action' menu](https://django-import-export.readthedocs.io/en/latest/admin_integration.html#exporting-via-admin-action).
- Return only 'pk' field
- Provide overrideable method
- Added tests
=> Added overridable method to restrict pks when exporting

docs/changelog.rst, import_export/widgets.py
**Problem**
widget module no longer needs to check for code pre django 3.* as it is now no longer supported.
**Solution**
- Removed outdated logic
- Test suite
=> removed outdated formatting of date strings

Makefile, docs/changelog.rst, import_export/mixins.py, tests/core/tests/test_mixins.py
**Problem**
Closes #1823 
Re-added the deprecation warnings from v3.
Now if you declare:
```python
class BookAdmin(ImportExportModelAdmin):
list_display = ("name", "author", "added")
list_filter = ["categories", "author"]
resource_class = BookResource
change_list_template = "core/admin/change_list.html"
```
You will see the following warning if you enable deprecation warnings, and browse to the import or export page in the UI:
```
python -X dev ./manage.py runserver
DeprecationWarning: The 'resource_class' field has been deprecated. Please implement the new 'resource_classes' field
```
- Re-added tests
=> re-add `resource_class` deprecation warning

docs/changelog.rst, import_export/admin.py, tests/core/tests/admin_integration/test_action_export.py
**Problem**
If an model has a custom pk (e.g. `UUIDCategory`) then an export via the instance page would cause a crash.
**Solution**
replaced reference to `obj.id` with `obj.pk`
- Added test
=> Fix crash on export from action when instance has custom PK

docs/changelog.rst, import_export/forms.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/test_forms.py
**Problem**
See @matthewhegarty under #1846 
**Solution**
I added both filed name and column name into the output:
I didn't wrote any tests, but I can if they would help.
=> Export from admin: display both field name and column_name (if available)

docs/admin_integration.rst, docs/advanced_usage.rst, docs/changelog.rst, docs/faq.rst, import_export/declarative.py, import_export/fields.py, import_export/resources.py, import_export/widgets.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_fields.py, tests/core/tests/test_resources/test_import_export.py, tests/core/tests/test_resources/test_modelresource/test_export.py
**Problem**
Closes #1874 #1872 
If a Resource has declared fields with no attribute declaration, then there should be no attempt to set attributes on the resource.  This is the v3 behaviour.
**Solution**
Reverted changes from #1861 which set attribute if not defined.
Added tests and documentation to confirm the behaviour.
=> Revert setting `attribute` for declared fields with no attribute declared

tests/core/tests/admin_integration/test_action_export.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/admin_integration/test_import.py
Tests were using `str(response.content)` to converts bytes values to strings. But this method converts to string using `repr()`, giving the associated `b` prefix, quotes, and escaping:
```ipython
In [1]: str(b'<!doctype html>...')
Out[1]: "b'<!doctype html>...'"
```
This PR adjusts all such conversion in tests to use the correct method, `bytes.decode()`.
(Spotted whilst working on #1882.)
=> Fix response content assertions

.pre-commit-config.yaml, import_export/admin.py, import_export/declarative.py, import_export/forms.py, import_export/resources.py, import_export/results.py, tests/core/tests/admin_integration/mixins.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_mixins.py, tests/core/tests/test_resources/test_import_export.py, tests/core/tests/test_resources/test_modelresource/test_export.py, tests/core/tests/test_resources/test_modelresource/test_resource.py, tests/core/tests/test_widgets.py
They’re clearer and a little bit faster, per [rule C408 in flake8-comprehensions](https://github.com/adamchainz/flake8-comprehensions?tab=readme-ov-file#c408-unnecessary-dictlisttuple-call---rewrite-as-a-literal) (which I’d be happy to add to the setup, if you want).
=> Use literals to create lists and dicts

import_export/resources.py, import_export/results.py, tests/core/tests/admin_integration/test_import.py, tests/core/tests/test_results.py
1. Lazily compute the traceback string, using `traceback.format_exception()`. It’s only used in the rare case that `"traceback"` is in the `import_error_display` attribute, so we can save that work and memory in the usual case.
2. Add a nice `__repr__`, to help debug test failures that make assertions on `Error` objects. I had a few cases where tests failed with inscrutable messages from pytest like `Left contains one more item: <import_export.results.Error object at 0x3173c8690>`, and I needed to rerun the test with the debugger to inspect the inner exception.
=> Improve Error class

import_export/resources.py, tests/core/tests/test_resources/test_import_export.py
Cast tuple onto the Meta order_fields so they can concatenate with the Meta fields.
On a class inheriting `resources.ModelResource`, when fields and order_fields are defined as list in the class' Meta, tuple is cast onto the `fields `attribute but not onto the `order_fields`.
This results in the TypeError on line 1121 coming from the line `defined_fields = order_fields + tuple(getattr(self._meta, "fields") or ()`
(.../import_export/resources.py)
Now both resources.ModelResource - Meta - fields and order_fields can be defined as list.
Casting the tuple build in function onto the order_fields too.
=> Casting tuple onto the order_fields attribute in _get_ordered_field_names

docs/changelog.rst, import_export/tmp_storages.py, tests/core/tests/test_tmp_storages.py
**Problem**
Closes #1888 
**Solution**
Remove the version check and associated tests.
All tests pass.
=> Remove django version check for custom storages

docs/changelog.rst, import_export/resources.py, tests/core/tests/test_resources/test_modelresource/test_deprecated_fields.py
**Problem**
PR #1886 dropped the `return` line from `get_fields()`. Consequently, I saw crashes in my project like: `'NoneType' object is not iterable` , from methods calling `get_fields()`.
When deprecating a function, it shouldn't change beyond adding the warning. That gives users time to migrate off using it.
**Solution**
Restored the removed line.
Updated the unit test.
=> Restore return value for Resource.get_fields()

import_export/fields.py
**Problem**
`self.column_name` is set in `Field.__init__`, so the `__repr__` method can assume it exists, no need to use `getattr()`.
**Solution**
Used a plain attribute access.
Tests pass.
=> Remove use of getattr() in Field.__repr__()

import_export/mixins.py, tests/core/tests/test_mixins.py
**Problem**
Before, these warnings would report the message for the given lines within `import_export`, with no indication of which class needs fixing. That means users have to resort to grepping for the deprecated method name or turning the warning into an error to get a stack trace.
**Solution**
Added full path to the warning messages.
Updated tests for the new messages. Additionally, simplified them a bit by using the non-regex [`assertWarns()`](https://docs.python.org/3.12/library/unittest.html#unittest.TestCase.assertWarns).
=> Add class path to deprecated method warnings

docs/changelog.rst, import_export/mixins.py, tests/core/tests/test_mixins.py, tests/core/views.py
**Problem**
The existing warning added in #1667 did not reveal which class used the deprecated mixin.
**Solution**
Transform this warning to run at class definition time using [`object.__init_subclass__`](https://docs.python.org/3.12/reference/datamodel.html#object.__init_subclass__). Then the deprecated line is shown as the point of class definition.
Tested in my own project. Modified the tests here, though none check the warning message.
=> Improve warning for ExportViewFormMixin

AUTHORS, import_export/admin.py, tests/core/tests/admin_integration/test_import.py
**Problem**
#1901
**Solution**
When the confirm_form is invalid, the user will now be redirected back to the confirm page, with confirm_form errors passed as context, ensuring that appropriate validation errors are presented to the user .
Added tests.
Ran existing test suite.
=> Handle invalid confirm_form while importing

.pre-commit-config.yaml, import_export/admin.py, tests/scripts/bulk_import.py
Upgrade Black to this year’s major version, 24, which comes with [some style changes](https://black.readthedocs.io/en/stable/change_log.html#id18). Also, change to the mirror repo, a new option recommended by the [pre-commit integration docs](https://black.readthedocs.io/en/stable/integrations/source_version_control.html) for speed.
=> Upgrade Black

pyproject.toml
Update the minimum version in `dependencies` to 4.2, which is the minimum tested version. I believe this was missed in #1790, which removed Django 3.2 support.
=> Update Django version in dependencies

import_export/resources.py
`inspect.getmro()` [maps to reading `__mro__`](https://github.com/python/cpython/blob/dc93d1125f594ac7aece98558eaf33d09c348519/Lib/inspect.py#L747-L749) ([`__mro__` docs](https://docs.python.org/3.12/library/stdtypes.html#class.__mro__)), so use that for clarity and a slight performance improvement.
=> Swap inspect.getmro() for __mro__ attribute

docs/changelog.rst, pyproject.toml, tox.ini
Django 5.1 is in release candidate as of last week: https://www.djangoproject.com/weblog/2024/jul/24/django-51-rc1/
This PR adds it to the test matrix and corrects the tox configuration for 5.0, which would accidentally have started testing 5.1 upon its release.
=> Support Django 5.1

docs/changelog.rst, docs/installation.rst, import_export/declarative.py
**Problem**
Closes #1902 
**Solution**
Added a log warning if a field is excluded.
- Enable [logging](https://django-import-export.readthedocs.io/en/latest/installation.html#configure-logging), run the test suite, and you will see the warning message.
=> Added warning log for declared fields excluded from fields whitelist

docs/changelog.rst, import_export/widgets.py, tests/core/tests/test_widgets.py
Fixes #1927.
An alternative approach to #1928, trying to make export-import work as a roundtrip in most languages.
This does have the weird behaviour that if you export in one language and import in another, that might not work. But that’s already the case since #1025, if the two languages have different numeric separators.
Tested by new widget unit tests plus trying using the test project in French.
=> Accept locale numeric separators in imported numbers

docs/advanced_usage.rst, docs/changelog.rst, import_export/admin.py, pyproject.toml, requirements/base.txt, requirements/test.txt, tests/core/tests/admin_integration/test_import_functionality.py, tox.ini
**Problem**
Closes #1937 
**Solution**
The problem was that 'skip' and 'error' rows are included when writing `LogEntry`.  This is a regression from v3, where these rows are ignored.
Added tests which proves the fix.
=> Fix crash for Django 5.1 when rows are skipped

docs/changelog.rst, import_export/admin.py, tests/core/tests/admin_integration/mixins.py, tests/core/tests/test_permissions.py
**Problem**
Even if the user does not have permission to export, "Export..." will still show up in the dropdown action, and only errors out later when the export is submitted.
**Solution**
Add a permission check in "get_actions"
Run several local tests.
=> Avoid showing export action when there's no permission

docs/advanced_usage.rst, docs/changelog.rst, import_export/fields.py, import_export/resources.py, tests/core/tests/test_fields.py, tests/core/tests/test_resources/test_modelresource/test_relationship.py
**Problem**
Can't reuse a `dehydrate` function across multiple Fields
**Solution**
Allow a callable to be set as the `dehydrate_method`
Run several local tests.
=> Allow callable in dehydrate_method

README.rst, docs/advanced_usage.rst, docs/changelog.rst, import_export/declarative.py, import_export/resources.py, tests/core/admin.py, tests/core/tests/admin_integration/test_export.py, tests/core/tests/test_resources/test_modelresource/test_export.py, tests/core/tests/test_resources/test_modelresource/test_resource_fields.py
**Problem**
Closes #1959
**Solution**
- Now a `warning` is issued rather than raising a `ValueError`
- Also updated log warning in `declarative.py` to warning (as per [this comment](https://github.com/django-import-export/django-import-export/pull/1930/files#r1704297805))
- Added tests
=> Fix crash when Resource fields declared incorrectly

runtests.sh, tests/docker-compose.yml
**Problem**
Waiting for 45seconds during a full run of the tests is time consuming
**Solution**
Use the native docker-compose health checks
=> Improve docker compose local runtests.sh script

Makefile, docs/changelog.rst, docs/testing.rst
**Problem**
Last commit to main specified incorrect format for `pip install`.
This PR corrects it.
=> fixed pip install docs

import_export/resources.py
When tryin to fix tests or see why the import does not work, i usually get a cryptic error message not pointing to the part of the code that failed. It just gives the exception but not where it comes from. By adding exc_info=True, the traceback is visible and its much easier to debug. Also i think warning level should be used instead of debug for these import errors
**Problem**
**Solution**
=> Chore: improve logging for debugging purposes

docs/celery.rst
**Problem**
Run import/export in background
**Solution**
Extend `django-import-export` in another open-source package
> Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes? 
There are only changes of documentation
---
Hi everyone!
This package is great, but we often needed the functionality of background tasks. So, we decided to extend `django-import-export` to support Celery. Along the way, we added several additional features.
Now, we’re excited to share it with the community! I think it would be helpful to include a link to another solution that provides Celery integration.
=> Extend "Using celery" section in docs

docs/changelog.rst, import_export/admin.py, import_export/widgets.py, tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1995 
**Solution**
Added check for binary format in `DateTimeWidget` and remove tzinfo if so.
- added tests
=> Fix crash when exporting tz-aware datetime instances

import_export/widgets.py, tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1995 
**Solution**
Move check so that empty fields (None) are handled before datetime update logic.
- Added test
=> Added test for empty datetime field

docs/changelog.rst, import_export/results.py, tests/core/tests/test_results.py
**Problem**
This commit introduces a `__repr__` method for InvalidRow, allowing exceptions to be more easily inspected during debugging.
**Solution**
Adding `__repr__` method :shrug: 
=> Add __repr__ method to InvalidRow for improved debugging

import_export/mixins.py
… mixins.py
1. Improved the docstring description for better clarity:
Changed `:returns: The export Resource class` to `:returns: The import Resource class`.
=> Fix Typo in BaseImportMixin Documentation

tests/core/tests/test_resources/test_import_export.py, tox.ini
**Problem**
There was a [line](https://coveralls.io/builds/71753409/source?filename=import_export%2Ffields.py#L106) missed by test coverage.
**Solution**
Added a single test to fix coverage
Ran existing test suite.
=> added field test to fix line missed by test coverage

docs/advanced_usage.rst, docs/faq.rst
**Problem**
It looks like there is an error in the documentation do with handling non-existent relations during import.
The docs [here](https://django-import-export.readthedocs.io/en/4.3.4/advanced_usage.html#creating-non-existent-relations) describe creating non-existent relations by overriding `before_import_row()` and creating relations there.  
However the flaw in this is that although it will create the relations, it will not associate the relations with the instance being imported.
It would work if the `id` was in the dataset:
```python
def before_import_row(self, row, **kwargs):
author_id = row["author"]
Author.objects.get_or_create(id=author_id, name="J. R. R. Tolkien")
```
But this is not what is currently documented, and it is quite difficult to understand exactly what is going …
=> Update 'Creating non-existent relations' documentation

.pre-commit-config.yaml, import_export/forms.py
**Problem**
Make pyupgrade upgrade source to Python 3.9+ syntax.
**Solution**
Updated target version. (This was missed when Python 3.8 was dropped in #1979.)
`pre-commit run pyupgrade --all-files` made one change, an import update, included in this commit.
=> Update pyupgrade target version to 3.9

AUTHORS, import_export/resources.py
**Problem**
The previous implementation of `bulk_create`, `bulk_update`, `bulk_delete` had redundant conditional checks that could be simplified. Specifically, the nested condition:
```python
if len(self.instances) > 0:
if not using_transactions and dry_run:
pass
````
could be merged into a more concise, readable statement. The existing logic was unnecessarily verbose and harder to maintain, especially as similar conditions appear elsewhere in the codebase.
**Solution**
I simplified the conditional logic by combining the checks into a single if statement and move the try except inside the if:
```python
if len(self.instances) > 0 and (using_transactions or not dry_run):
try:
....
```
This improves readability by removing unnecessary nesting while maintaining the original logic. Also …
=> Improve logic of bulk create, update and create methods

docs/contributing.rst
Update the instructions for installing optional dependencies in the contributing guide.
`pip install .[tests]` didn't work.
I also added `python -m` in front of the `pip install ..` commands, because this is a better way to invoke pip, and also because you already have other examples using `python -m `.
**Problem**
I tried following the steps for running tests locally from the contributing guide.
I found the step `pip install .[tests]` doesn't work.
**Solution**
`pip install '.[tests]'` works.
I tried using pip 25.0.1..
```
pip install .[tests]            
zsh: no matches found: .[tests]
```
```
pip install '.[tests]'
Processing /Users/mariatta/github/django-import-export
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing …
```
=> Fix typo in contributing Guide

AUTHORS, import_export/declarative.py, tests/core/tests/test_resources/test_modelresource/test_resource_fields.py
Closes: https://github.com/django-import-export/django-import-export/issues/2017
**Problem**
Per https://github.com/django-import-export/django-import-export/issues/2017, warnings were being logged for subclasses using a subset of a parent resource's fields
**Solution**
Updated `ModelDeclarativeMetaclass` to track each specific classes' fields and only warn if that classes declared fields are not listed in the fields property.
I also added the class name to the warning to help assist users in finding the class in question.
I added tests that define resource subclasses with and without missing declared fields and check that the correct warnings are logged.
=> Warn for unused fields declared on class only

AUTHORS, docs/changelog.rst, import_export/static/import_export/export_selectable_fields.js, import_export/templates/admin/import_export/export.html
**Problem**
Solves #2067, which requires  **Select All / De-select all** toggle option for the export flow checkboxes
**Solution**
Added **Select All / De-select all** toggle button in admin model export flow
Toggling checkboxes not affecting any existing flow, as its a UI side feature to provide ease to end user
=> Select deselect feature

docs/admin_integration.rst
**Problem**
The documentation in [Customize admin import forms](https://django-import-export.readthedocs.io/en/latest/admin_integration.html#customize-admin-import-forms) was incorrect:
The function `after_init_instance` must be added to the `BookResource` class (subclass of `Resource`) instead of the `CustomBookAdmin` class. 
**Solution**
I updated the documentation accordingly.
Only documentation was changed/fixed.
=> Fix "Customize admin import forms"

import_export/resources.py, tests/core/tests/test_resources/test_modelresource/test_resource_factory.py
**Problem**
The `modelresource_factory` is not very customizable w.r.t. meta items.
**Solution**
By adding a parameter, one can inject extra data into the `Meta`.
written a test for this.
=> Allow specifying meta options in the modelresource_factory, fixing #20177

AUTHORS, docs/advanced_usage.rst, docs/changelog.rst, docs/getting_started.rst, import_export/resources.py, tests/core/tests/test_resources/test_modelresource/test_resource_factory.py
**Problem**
modelresource_factory function had limited customization capabilities
**Solution**
Added custom_fields, dehydrate_methods parameters to `modelresource_factory` 
tests written for new functionality and added usage documentation in getting_started.rst
issue: #2080
=> Allow custom fields and methods in modelresource_factory

AUTHORS, docs/release_notes.rst
**Problem**
Typo in save_instance Function Signature in Release Notes: ***kwargs Should Be **kwargs
**Solution**
Removed extra asterisks from the function signature parameter
Screenshot of changes:
=> Updates save instance function signature in release notes

import_export/admin.py
**Problem**
Now that Django 5.0 is no longer supported, this code block is unreachable.
**Solution**
Removed the redundant code and ran the tests.
=> removed unreachable code
