django-import-export/django-import-export

- docs/getting_started.rst
> document export_order option

- import_export/admin.py
Simple fix based on #244 issue
> to_encoding functionality

- import_export/locale/es/LC_MESSAGES/django.po
> Fix typo errors

- docs/settings.rst
- import_export/admin.py
> Allow override of tmp_storage_class in settings

- import_export/resources.py
> use the IntegerWidget for database-fields of type BigIntegerField

- docs/getting_started.rst
Just checking out your project and saw a typo. Thanks for your work.
> Correct minor typo

- import_export/locale/es/LC_MESSAGES/django.po
Finish word translation fixed.
> Fixed typo error

- import_export/widgets.py
- tests/core/tests/widgets_tests.py
> m2m widget: allow trailing comma

- import_export/fields.py
- import_export/resources.py
- tests/core/models.py
- tests/core/tests/resources_tests.py
This PR changes behavior for empty values to default to model default. cc @bmihelac
> Support default values on fields (and models)

- .travis.yml
- import_export/admin.py
- import_export/resources.py
- tests/settings.py
- tox.ini
> fixes for Django 1.10, test in allow-failure mode

- .travis.yml
> Drop django 1.5 tests, exclude py3.5 against django<1.9

- import_export/tmp_storages.py
- tests/core/exports/books-mac.csv
- tests/core/tests/admin_integration_tests.py
- tests/core/tests/base_formats_tests.py
- tests/core/tests/tmp_storages_tests.py
> Added support for the file mode to MediaStorage.read()

- docs/getting_started.rst
It helps noobs (like me) if you include all the code needed... in this one the import was missing from the sample.
> Make sample more explicit

- import_export/formats/base_formats.py
This is for passing delimiter argument to csvwriter. 
For importing Kenneth Reitz just added delimiter in https://github.com/kennethreitz/tablib/commit/70716fdd216755dc4b542df74e95b0e5ac74f0ee
> add **kwargs to export_data / create_dataset 

- import_export/resources.py
To match the functionality with before/after importing when exporting.
> Add before_export() and after_export()

- import_export/admin.py
- import_export/resources.py
> Expose Django user to get_export_data() and export()

- import_export/admin.py
- import_export/resources.py
Matches call to resource.import_data().
> Pass Django user to resource.get_fields() in ImportMixin.import_action()

- docs/import_workflow.rst
- import_export/resources.py
To customize behaviour before and after individual rows are imported.
> Add before_import_row() and after_import_row()

- import_export/admin.py
> Configure user parameter in resource from kwargs

- import_export/admin.py
- import_export/resources.py
Control what fields are visible to the user in both the diff and the list of fields to be imported
> Control user-visible fields

- import_export/admin.py
- import_export/resources.py
- tests/core/tests/admin_integration_tests.py
Fixes #474
This fix only applies to import - the export view requested via GET results in just the form.
> require POST method + test

- import_export/resources.py
- tests/core/tests/admin_integration_tests.py
Fix exception generating log entries when import is confirmed and Resource.import_data() is called with raise_errors=False
> Fix exception in generate_log_entries()

- docs/conf.py
- requirements/dev.txt
Also add sphinx-rtd-theme as an explicit dev dependency
> Add intersphinx links to documentation

- CONTRIBUTING.md
- setup.py
Updating both the CONTRIBUTING documentation as well as the url defined
in setup tools for the package.
> GitHub bmihelac -> django-import-export Account Update

- import_export/templates/admin/import_export/base.html
As some other apps also add specific body classes in admin/base_site.html block bodyclass should call block.super.
> Added {{ block.super }} call in block bodyclass in admin/base_site.html

- docs/changelog.rst
Based on @beruic's #593.
The only thing I left out was #670 since it was just fixing the spelling of a name in the AUTHORS document.
> Full 0.5.2 changelog

- AUTHORS
Recommended by @mgrdcm in #633
> Add myself to the list of AUTHORS

- .travis.yml
2.0 not completely supported by this package yet, but at least wanted to get them into the list.
> Travis tests for Django 2.0.x

- AUTHORS
- docs/getting_started.rst
> Resolves #703 fields shadowed

- import_export/fields.py
- import_export/resources.py
- tests/core/fixtures/book.json
- tests/core/tests/resources_tests.py
> use ManyToManyRelatedManager.set method to save m2m fields

- import_export/widgets.py
Adds import statements to the example in the ForeignKeyWidget docblock.
> Edit docblock for ForeignKeyWidget

- import_export/resources.py
- tests/core/tests/resources_tests.py
> Restore raise_errors to before_import

- requirements/dev.txt
https://docs.djangoproject.com/en/2.0/ref/databases/#mysql-db-api-drivers
> use Python3 compatible MySql driver in development

- README.rst
I noticed in another PR, that our coverage is actually around ~94%. Woohoo! It's like finding 5 dollars in a pair of old pants!
> Use coveralls master branch badge in Readme

- setup.py
**Problem**
Display project description on https://pypi.org/project/django-import-export/
> chore: add package long_description

- import_export/admin.py
**Problem**
Fixes: https://github.com/django-import-export/django-import-export/issues/873
**Solution**
Docs
> Expand doc strings to include Mixin superclasses

- .travis.yml
- requirements/test.txt
- tests/core/tests/test_widgets.py
- tests/settings.py
---
name: Pull Request
about: Create a PR to contribute
title: ''
labels: ''
assignees: ''
---
**Problem**
**Solution**
**Screenshots**
If applicable, add screenshots to help explain your solution.
Please make sure you meet the following.
> Add mysql to travis

- requirements/dev.txt
per https://github.com/django-import-export/django-import-export/issues/890
> chore: add python wheels to dev requirements (#890)

- docs/changelog.rst
- import_export/resources.py
- import_export/widgets.py
- tests/core/migrations/0004_bookwithchapters.py
- tests/core/models.py
- tests/core/tests/test_resources.py
- tests/settings.py
**Problem**
#285 
**Solution**
Add jsonb field to the resource field mapping.  Also added some more tests for array field data import.
**Screenshots**
If applicable, add screenshots to help explain your solution.
NA
Please make sure you meet the following.
> Add JSON B type field

- docs/getting_started.rst
Admin example was not turnkey.
I added a few more lines so the Admin integration shows all the code you'd need.
> Complete example for admin integration

- docs/getting_started.rst
**Problem**
wrong style in `getting_started` docs
**Solution**
fix style
no tests and no screenshot required I thought.
> fix style in getting_started docs

- .travis.yml
**Problem**
3.8 release is coming up in a few months, so we should be prepared for any changes
**Solution**
Add 3.8 to travis CI
> Add 3.8-dev to travis ci

- .travis.yml
> Simply Django version in TravisCI

- docs/changelog.rst
- docs/installation.rst
- import_export/utils.py
- tests/core/tests/test_invalidrow.py
> Fix typos in docs and comments

- .travis.yml
- setup.py
- tox.ini
Add real support of Django 2.2 before 3.0 is out
> [django2.2] Add real support of Django 2.2 before 3.0 is out

- import_export/admin.py
- import_export/resources.py
- import_export/static/import_export/action_formats.js
- tests/core/tests/test_resources.py
**Problem**
Fix #1006
**Solution**
Remove use of deprecated jQuery
Ensure correct order of JS media
This is hard to test formally, so someone please verify it.
> Update jquery fix #1006 for 1.x

- .travis.yml
- README.rst
- docs/conf.py
- docs/import_workflow.rst
- docs/index.rst
- import_export/formats/base_formats.py
- requirements/base.txt
- setup.py
- tox.ini
tablib recently changed home (code and docs).
> Updated tablib links and usage

- .travis.yml
- import_export/resources.py
- tests/core/tests/test_resources.py
closes django-import-export/django-import-export/issues/1055
> Use column_name when checking row for fields

- import_export/widgets.py
> Typo fix in widgets.py

- README.rst
- docs/installation.rst
- tests/books-sample.csv
- tests/core/fixtures/book.json
- tests/core/fixtures/category.json
**Problem**
The Demo was set up with not data. 
**Solution**
Using the existing fixtures to give the Demo app more options for interaction by the users. Also, add a CSV file which can be imported.
Update the documentation. Also, include the additional steps due to the removal of the migrations in #1126.
> Update the demo app

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
Github Issue templates. Addresses #1134
> Update issue templates

- import_export/locale/ar/LC_MESSAGES/django.po
- import_export/locale/bg/LC_MESSAGES/django.po
- import_export/locale/ca/LC_MESSAGES/django.po
- import_export/locale/cs/LC_MESSAGES/django.po
- import_export/locale/de/LC_MESSAGES/django.po
- import_export/locale/es/LC_MESSAGES/django.po
- import_export/locale/es_AR/LC_MESSAGES/django.po
- import_export/locale/fr/LC_MESSAGES/django.po
- import_export/locale/it/LC_MESSAGES/django.po
- import_export/locale/ja/LC_MESSAGES/django.po
- import_export/locale/nl/LC_MESSAGES/django.po
- import_export/locale/pl/LC_MESSAGES/django.po
- import_export/locale/pt_BR/LC_MESSAGES/django.po
- import_export/locale/ru/LC_MESSAGES/django.po
- import_export/locale/sk/LC_MESSAGES/django.po
- import_export/locale/tr/LC_MESSAGES/django.po
- import_export/locale/zh_Hans/LC_MESSAGES/django.po
**Problem**
There are some strings which did not have the key in the .po files
**Solution**
run `django-admin.py makemessages --all`
> Add missing translation keys for all languages

- import_export/locale/pt_BR/LC_MESSAGES/django.po
**Problem**
Missing translations in portuguese
**Solution**
Added missing portuguese translations
Verified with native speaker
> Added missing Portuguese translations

- docs/installation.rst
> Fix typo in installation.rst

- docs/installation.rst
> Fix minor mistake in makemigrations command

- .travis.yml
- tox.ini
> Update django master to django main

- README.rst
**Problem**
a proper readable way in readme file
> Correct typo in Readme

- import_export/resources.py
**Problem**
Two docstrings incorrectly phrased logical conditions. 
**Solution**
Suggest new formulations that match the logical branching conditions.
Commit messages describe the rational of the changes in detail.
> Rephrase logical clauses in docstrings

- docs/changelog.rst
- setup.py
- tox.ini
**Problem**
Django 4.0 is released, so have added support in this project.
**Solution**
- updated tox.ini
- updated setup.py
- Ran all tox tests from scratch
> Added support for Django 4.0

- .github/workflows/django-import-export-ci.yml
**Problem**
Django 4 was missing from CI config
**Solution**
Have added reference to django4
Testing using CI builds
> added 4.0 django-version to CI build

- docs/installation.rst
> Fix broken link to tablib formats page

- CONTRIBUTING.md
Since that's what it's actually called on this project
> Contributing should refer 'main' not 'master'

- docs/changelog.rst
- import_export/resources.py
- tests/core/admin.py
- tests/core/tests/test_resources.py
**Problem**
Use keyword arguments for resource classes
**Solution**
add kwargs to resource class constructor and assign to instance variable.
> Use keyword arguments for resource classes

- .github/workflows/django-import-export-ci.yml
- tests/core/tests/test_widgets.py
- tests/settings.py
- tox.ini
**Problem**
Tox failing due to latest django changes
**Solution**
- updated tox.ini 
- updated CI file (upgraded to tox 4)
- fixed failing tests
- modified settings
Tox tests pass
> tox updates

- import_export/locale/de/LC_MESSAGES/django.po
Hej @matthewhegarty, 
sorry for being late. here is the follow-up PR from #1533 
It is challenging to see in the PO file. For this reason, I am not 100% sure that the German translations are complete. If you add more Msgid or if German translations are still missing, you can ping me, and I will try to help with my german skills.
> update missing translation

- AUTHORS
- import_export/locale/es/LC_MESSAGES/django.po
- import_export/locale/es_AR/LC_MESSAGES/django.po
**Problem**
Added more texts to Spanish and Spanish (Argentina) translation files.
**Solution**
N/A
N/A
> Added new translations to Spanish and Spanish (Argentina)

- docs/changelog.rst
- setup.py
- tox.ini
Added support for Django 4.2 released April 3rd
> added support for Django 4.2

- docs/getting_started.rst
Fix a type in getting_started.rst file
> Fix a type in getting_started.rst file

- docs/changelog.rst
> prepare 3.3.0 release

- docs/advanced_usage.rst
- docs/changelog.rst
- import_export/resources.py
**Problem**
Closes #1653
**Solution**
Updated documentation
Built and reviewed on dev pc.
> Clarified 'skip_diff' documentation

- AUTHORS
- docs/advanced_usage.rst
- docs/getting_started.rst
**Solution**
Added myself to the list of authors
> Updated the list of authors

- docs/changelog.rst
- import_export/resources.py
- tests/core/tests/test_resources.py
**Problem**
Closes #1517 
Helps with debugging errors with the configuration of the Resource.
**Solution**
Added debug logging and tests.
(I had to make minor adjustments to existing tests)
Test suite runs as expected.
> Add logging for missing fields & attributes

- docs/changelog.rst
- docs/faq.rst
**Problem**
Added FAQ entry to help those exporting large datasets.
**Solution**
Updated docs.
Built and checked docs locally before committing.
> Update FAQ to include details on exporting large datasets

- docs/changelog.rst
- import_export/admin.py
- tests/core/tests/test_admin_integration.py
**Problem**
Fix for #1714 
**Solution**
Described at #1714 
I didn't yet write tests and documentation. I would like to get some feedback first.
> avoid unnecessary COUNT queries when exporting

- docs/changelog.rst
- import_export/mixins.py
- tests/core/tests/test_admin_integration.py
- tests/core/tests/test_mixins.py
**Problem**
#1741 
**Solution**
Followed Suggested Approach. Implemented Two Tests.
Have you written tests?
-Yes
Have you included screenshots of your changes if applicable?
-NA
Did you document your changes? 
-Yes
> #1741 Unit & Integration Test added for changes suggested. 

- docs/changelog.rst
- tests/core/tests/test_resources/test_modelresource/test_error_handling.py
**Problem**
Closes #1752 
Increase test coverage
**Solution**
Added a test to cover missing line.
> Add test to cover `collect_failed_rows` for validation errors

- docs/changelog.rst
- import_export/widgets.py
- tests/core/admin.py
- tests/core/tests/test_base_formats.py
> fix: YAML export does not work with SafeString (#1324)

- import_export/exceptions.py
- import_export/resources.py
- tests/core/tests/admin_integration/test_import.py
- tests/core/tests/test_resources/test_import_export.py
- tests/core/tests/test_resources/test_modelresource/test_error_handling.py
**Problem**
Closes #1764 
**Solution**
- Modified the error message
- Ensure that error only raised to caller if `raise_errors` is True
- Updated tests
> Refactor _check_import_id_fields()

- docs/changelog.rst
- import_export/resources.py
- tests/core/tests/test_resources/test_modelresource/test_data_import.py
**Problem**
Closes #1768 
**Solution**
Added the param as suggested
- Added test
> pass is_create into `do_save_instance()`

- docs/changelog.rst
- docs/installation.rst
- import_export/admin.py
- tests/core/admin.py
- tests/core/models.py
- tests/core/tests/admin_integration/mixins.py
- tests/core/tests/admin_integration/test_action_export.py
- tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1800 
**Solution**
- Use `pk` not `id`
- Added test
> Fix crash on export for Model with custom pk

- docs/changelog.rst
- import_export/declarative.py
- import_export/resources.py
- tests/core/admin.py
- tests/core/forms.py
- tests/core/tests/admin_integration/test_export.py
- tests/core/tests/admin_integration/test_import.py
- tests/core/tests/test_resources/test_modelresource/test_export.py
**Problem**
Closes #1808
**Solution**
Refactored methods used during export.
Updated 'Ebook' tests to check for this condition.
> Handle custom column name during export

- docs/changelog.rst
- import_export/resources.py
- tests/core/admin.py
- tests/core/tests/admin_integration/test_export.py
- tests/core/tests/admin_integration/test_import.py
**Problem**
Closes #1828 
**Solution**
Add additional check for column name when checking fields for export
- Added test
> fix crash on export with custom column name

- docs/advanced_usage.rst
- docs/changelog.rst
- docs/faq.rst
- docs/release_notes.rst
- import_export/resources.py
- tests/core/tests/test_resources/test_import_export.py
**Problem**
Closes #1834
Clarify usage when importing with 'dynamic' fields
**Solution**
- Updated documentation
- Ran tests
- Added new test
- Ran existing test suite
> Clarified documentation when importing with `import_id_fields`

- README.rst
- docs/changelog.rst
- docs/release_notes.rst
Clarified that `resource_class` declaration is deprecated in v4
> Release note documentation update

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.rst
- RELEASE.md
- docs/changelog.rst
- pyproject.toml
**Problem**
Publish to PyPI failed due to invalid README.rst
**Solution**
Corrected duplicate links in the README
Confirmed successful build on TestPyPI
> Fix issue with invalid README.rst

- docs/admin_integration.rst
- docs/changelog.rst
- tests/core/forms.py
- tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1858
**Solution**
- Corrected documentation
- Added test to prove that the export process works as documented. 
- All tests pass
> fix documentation to show correct method for reading form data on export

- docs/changelog.rst
- docs/faq.rst
- docs/release_notes.rst
**Problem**
Documentation was unclear wrt changes to CharField.  Have clarified.
Closes #1855
> clarify changes to CharWidget in v4

- docs/changelog.rst
- import_export/resources.py
Small refactor as discussed on #1846
> refactor: de-duplicate Resource.get_export_headers() and export_resource()

- docs/advanced_usage.rst
- docs/changelog.rst
- docs/release_notes.rst
**Problem**
Closes #1850
**Solution**
Minor changes to docs.
> Clarify documentation on widget configuration

- docs/changelog.rst
- docs/getting_started.rst
`for_delete()` documentation wasn't clear.  I provided a simplified example
> clarified `for_delete()` docs

- docs/changelog.rst
- docs/release_notes.rst
- import_export/resources.py
- tests/core/tests/test_resources/test_modelresource/test_deprecated_fields.py
- tests/core/tests/test_resources/test_modelresource/test_relationship.py
- tests/core/tests/test_resources/test_modelresource/test_resource_transactions.py
**Problem**
Closes #1885 
**Solution**
Deprecated the existing method.
> deprecated unused `get_fields()` method

- docs/advanced_usage.rst
- import_export/options.py
**Problem**
Closes #1907 
**Solution**
Updated documentation
> docs: added note to clarify use of `clean_model_instances`

- .pre-commit-config.yaml
- tests/core/admin.py
- tests/core/tests/admin_integration/test_import.py
- tests/core/tests/test_model_resource_fields_generate_widgets.py
- tests/settings.py
**Problem**
Use of deprecated or old Django featurse.
**Solution**
Added my tool [django-upgrade](https://github.com/adamchainz/django-upgrade) to pre-commit to automatically update syntax where possible. I made some manual tweaks to the fixes.
Unit tests
> Add django-upgrade to pre-commit

- .pre-commit-config.yaml
- import_export/admin.py
- import_export/fields.py
- import_export/mixins.py
- import_export/resources.py
- import_export/widgets.py
- tests/core/models.py
- tests/core/tests/admin_integration/mixins.py
- tests/core/tests/admin_integration/test_action_export.py
- tests/core/tests/admin_integration/test_export.py
- tests/core/tests/test_mixins.py
- tests/core/tests/test_permissions.py
- tests/core/tests/test_resources/test_modelresource/test_error_handling.py
- tests/core/tests/test_resources/test_modelresource/test_relationship.py
- tests/core/tests/test_results.py
- tests/core/tests/test_tmp_storages.py
- tests/core/tests/test_widgets.py
**Problem**
Code uses older Python syntax and features.
**Solution**
Added [pyupgrade](https://github.com/asottile/pyupgrade) to automatically upgrade syntax, and applied it everywhere.
Reviewed all changes and tests still pass.
> Add pyupgrade to pre-commit

- docs/changelog.rst
- import_export/forms.py
- import_export/templates/admin/import_export/import.html
- tests/core/tests/admin_integration/test_export.py
- tests/core/tests/test_forms.py
> Hide 'Resource' form field for one option

- import_export/widgets.py
- tests/core/tests/test_widgets.py
**Problem**
[1894](https://github.com/django-import-export/django-import-export/issues/1894)
**Solution**
Replace the `type` check in the render method with `isinstance`
Added tests.
Ran existing test suite.
> Update date, time and datetime widget render method to handle derived instance

- docs/changelog.rst
- docs/release_notes.rst
- pyproject.toml
- requirements/base.txt
- tests/core/tests/test_base_formats.py
**Problem**
Closes #1627 
**Solution**
Removed hard-coded references to tablib 3.5.1
Test runs
> Updated tablib version

- AUTHORS
- tests/core/tests/admin_integration/mixins.py
- tests/core/tests/admin_integration/test_action_export.py
- tests/core/tests/admin_integration/test_export.py
- tests/core/tests/admin_integration/test_import.py
- tests/core/tests/admin_integration/test_import_encoding.py
- tests/core/tests/admin_integration/test_import_errors.py
- tests/core/tests/admin_integration/test_import_functionality.py
- tests/core/tests/admin_integration/test_import_security.py
- tests/core/tests/admin_integration/test_import_templates.py
**Problem**
test_imports.py too long and has redundant code, Issue #1909
**Solution**
I split the code up into files and classes and added helper functions and used variables for the URLs
I did not write tests but used the existing tests
> Issue #1909 test_imports.py too long

- docs/changelog.rst
- docs/installation.rst
**Problem**
Closes #1868 
**Solution**
Documented how a model Admin attribute can be used to set formats.
Tested locally.
> updated 'formats' documentation

- tests/core/tests/admin_integration/test_import_functionality.py
**Problem**
Closes #1946 
**Solution**
Added tests
> added `skip_admin_log` integration tests

- docs/advanced_usage.rst
- tests/core/admin.py
- tests/core/tests/admin_integration/test_export.py
**Problem**
Tests issue raised in #1953
> Add test for declared field issue

- docs/advanced_usage.rst
- docs/installation.rst
- import_export/resources.py
**Problem**
Closes https://github.com/django-import-export/django-import-export/issues/1972
**Solution**
Updated docs and tested locally.
> Docs updates

- README.rst
- docs/admin_integration.rst
- docs/advanced_usage.rst
- docs/changelog.rst
- docs/faq.rst
- import_export/options.py
**Problem**
Fixed broken link in FAQ docs
Tested locally.
> Fix broken faq link

- import_export/widgets.py
- tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #1995.
The check for timezone was not being made correctly.
**Solution**
Moved the tz logic.
- added test
> added test for correct tz

- docs/advanced_usage.rst
- docs/changelog.rst
- docs/faq.rst
- docs/installation.rst
- import_export/admin.py
- import_export/formats/base_formats.py
- import_export/results.py
- pyproject.toml
- tests/core/tests/admin_integration/test_export.py
**Problem**
Closes #2000 
**Solution**
- Add config field which will sanitize invalid characters in Excel output
- Add error message instead of crash.
- Added test
- Tested manually
> Handle openpyxl ``IllegalCharacterError``

- .gitignore
- RELEASE.md
- docs/advanced_usage.rst
- docs/changelog.rst
- import_export/formats/base_formats.py
**Problem**
Closes #2004 
**Solution**
Moved package imports to methods
- Tested manually using issues steps to reproduce
- Ran unit tests
> fix issue with openpyxl imports

- docs/changelog.rst
> Prepare 4.3.5 release

- docs/changelog.rst
- pyproject.toml
- tox.ini
**Problem**
New Django is in alpha: https://www.djangoproject.com/weblog/2025/jan/16/django-52-alpha-1-released/
**Solution**
Added it to test grid
Tests pass with no new warnings.
> Support Django 5.2

- import_export/widgets.py
**Problem**
Closes #2030 
**Solution**
Tested condition and removed FIXME.
All existing tests pass.
> removed FIXME

- docs/changelog.rst
- import_export/templates/admin/import_export/import.html
- tests/core/tests/admin_integration/test_import_errors.py
**Problem**
Closes #2070 
**Solution**
Added the appropriate block to import.html
Added integration test.
Tested manually as per the bug report
> Fix display of non field errors on import

- docs/changelog.rst
- import_export/locale/ar/LC_MESSAGES/django.po
- import_export/locale/bg/LC_MESSAGES/django.po
- import_export/locale/ca/LC_MESSAGES/django.po
- import_export/locale/cs/LC_MESSAGES/django.po
- import_export/locale/de/LC_MESSAGES/django.po
- import_export/locale/es/LC_MESSAGES/django.po
- import_export/locale/es_AR/LC_MESSAGES/django.po
- import_export/locale/fa/LC_MESSAGES/django.po
- import_export/locale/fi/LC_MESSAGES/django.po
- import_export/locale/fr/LC_MESSAGES/django.po
- import_export/locale/he/LC_MESSAGES/django.po
- import_export/locale/it/LC_MESSAGES/django.po
- import_export/locale/ja/LC_MESSAGES/django.po
- import_export/locale/ko/LC_MESSAGES/django.po
- import_export/locale/kz/LC_MESSAGES/django.po
- import_export/locale/nl/LC_MESSAGES/django.po
- import_export/locale/pl/LC_MESSAGES/django.po
- import_export/locale/pt_BR/LC_MESSAGES/django.po
- import_export/locale/ru/LC_MESSAGES/django.po
- import_export/locale/sk/LC_MESSAGES/django.po
- import_export/locale/tr/LC_MESSAGES/django.po
- import_export/locale/zh_Hans/LC_MESSAGES/django.po
**Problem**
Prepare release 4.3.8.
**Solution**
- Updated changelog
- Re-built message files
Tests pass.
> Prepare release 4.3.8

- docs/changelog.rst
- docs/faq.rst
**Problem**
FAQ update to describe how to customize Excel exports
Tested local docs.
> FAQ update to describe how to customize Excel exports

- docs/contributing.rst
**Problem**
Clarified how to contribute translations.
> Translation update

- docs/admin_integration.rst
**Problem**
Updated documentation to handle SuspiciousOperation exception for larger exports.
**Solution**
Documented best practice to resolve this.
> documented handling TooManyFieldsSent
